# Generated by Django 4.1.9 on 2023-12-10 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user_management", "0008_alter_atlasgroup_slug"),
        ("webservice", "0107_log_alter_category_slug_alter_layer_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Authorization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resource", models.CharField(blank=True, max_length=255, null=True)),
                ("login_required", models.BooleanField(default=True)),
                ("response_filter", models.TextField(blank=True, null=True)),
                (
                    "atlas_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="De inhoud van dit endpoint kan alleen bekeken worden als de gebruiker lid is van een van deze groepen.",
                        to="user_management.atlasgroup",
                        verbose_name="Groepen",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webservice.source",
                    ),
                ),
            ],
        ),
    ]
