# Generated by Django 4.1.9 on 2023-12-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authz", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authorization",
            options={"ordering": ("source", "ordering")},
        ),
        migrations.AddField(
            model_name="authorization",
            name="ordering",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Sortering"
            ),
        ),
    ]
