# Generated by Django 4.1.9 on 2023-12-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authz", "0002_alter_authorization_options_authorization_ordering"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authorization",
            options={"ordering": ("source", "resource", "ordering")},
        ),
        migrations.AddField(
            model_name="authorization",
            name="description",
            field=models.CharField(
                default="-",
                help_text="Een beschrijvende tekst voor beheerders",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="authorization",
            name="response_filter",
            field=models.TextField(
                blank=True,
                help_text="Voeg een jq filter toe om een data response te filteren, in het geval van WMS GetFeatureInfo, WFS GetFeature en REST",
                null=True,
            ),
        ),
    ]
