# Generated by Django 4.1.9 on 2023-12-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authz", "0003_alter_authorization_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authorization",
            options={
                "ordering": ("source", "resource", "ordering"),
                "verbose_name": "Autorisatie",
                "verbose_name_plural": "Autorisaties",
            },
        ),
        migrations.AddField(
            model_name="authorization",
            name="audit_log",
            field=models.BooleanField(
                default=True, help_text="Voeg verzoeken toe aan de audit log"
            ),
        ),
    ]
