# Generated by Django 4.1.9 on 2023-12-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authz", "0004_alter_authorization_options_authorization_audit_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorization",
            name="login_required",
            field=models.BooleanField(
                default=True, verbose_name="Vereis inlog van gebruiker"
            ),
        ),
        migrations.AlterField(
            model_name="authorization",
            name="resource",
            field=models.CharField(
                blank=True,
                help_text="Naam van de laag of de resource",
                max_length=255,
                null=True,
            ),
        ),
    ]
