# Generated by Django 4.1.9 on 2023-12-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authz", "0005_alter_authorization_login_required_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(editable=False, max_length=255)),
                ("email", models.EmailField(editable=False, max_length=254)),
                ("source", models.CharField(editable=False, max_length=255)),
                ("resources", models.CharField(editable=False, max_length=255)),
                ("params", models.JSONField(editable=False)),
                ("time_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Log",
                "verbose_name_plural": "Logs",
                "ordering": ["-time_created"],
            },
        ),
    ]
