# Generated by Django 4.1.9 on 2023-12-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authz", "0006_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="log",
            name="user_agent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
