# Generated by Django 4.1.9 on 2023-12-10 17:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authz", "0007_log_ip_log_user_agent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="log",
            old_name="resources",
            new_name="resource",
        ),
    ]
