# Generated by Django 4.1.13 on 2025-04-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_alter_atlasgroup_slug'),
        ('authz', '0010_authorization_only_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorization',
            name='atlas_write_groups',
            field=models.ManyToManyField(blank=True, help_text='De inhoud van dit endpoint kan alleen bewerkt worden als de gebruiker lid is van een van deze groepen.', related_name='atlas_authz_write_groups', to='user_management.atlasgroup', verbose_name='Groepen'),
        ),
        migrations.AddField(
            model_name='authorization',
            name='authenticated_can_mutate',
            field=models.BooleanField(default=False, help_text='Alle ingelogde gebruikers kunnen wanneer deze optie aanstaat de laag of resource muteren', verbose_name='Ingelogde gebruikers kunnen de laag of resource muteren'),
        ),
    ]
