# Generated by Django 2.2.24 on 2021-06-07 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atlasgroup',
            options={'verbose_name': 'Groep', 'verbose_name_plural': 'Groepen'},
        ),
    ]
