# Generated by Django 3.2.7 on 2021-09-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20210607_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlasuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
