# Generated by Django 4.0.1 on 2023-05-04 09:03

from django.db import migrations, models


def move_to_name_field(apps, _):
    AtlasUser = apps.get_model('user_management', 'AtlasUser')

    for user in AtlasUser.objects.all():
        user.name = f'{user.first_name} {user.last_name}'
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20210607_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='atlasuser',
            name='name',
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name='Volledige naam'),
        ),
        migrations.RunPython(move_to_name_field, migrations.RunPython.noop),
    ]
