# Generated by Django 4.0.1 on 2023-05-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_atlasuser_name_alter_atlasuser_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlasuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
