# Generated by Django 4.1.9 on 2023-09-20 13:03

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0004_alter_atlasuser_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="atlasgroup",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                help_text="Een uniek kort kenmerk voor de groep.",
                populate_from="name",
                unique=True,
                verbose_name="Kort kenmerk",
            ),
        ),
    ]
