# Generated by Django 4.1.9 on 2023-09-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0006_atlasgroup_external_id_atlasuser_external_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atlasgroup",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="Het unieke kernmerk van de groep in de inlogbron.",
                max_length=255,
                null=True,
                verbose_name="External ID",
            ),
        ),
        migrations.AlterField(
            model_name="atlasuser",
            name="atlas_groups",
            field=models.ManyToManyField(
                blank=True, related_name="atlas_users", to="user_management.atlasgroup"
            ),
        ),
        migrations.AlterField(
            model_name="atlasuser",
            name="external_id",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Het unieke kernmerk van de gebruiker in de inlogbron.",
                max_length=255,
                null=True,
                verbose_name="External ID",
            ),
        ),
    ]
