# Generated by Django 4.1.9 on 2023-10-05 11:52

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0007_alter_atlasgroup_external_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atlasgroup",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                help_text="Een uniek kort kenmerk voor de groep.",
                null=True,
                populate_from="name",
                unique=True,
                verbose_name="Kort kenmerk",
            ),
        ),
    ]
