# Generated by Django 4.1.13 on 2025-03-11 14:01

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_alter_atlasgroup_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlasgroup',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='Een uniek kort kenmerk voor de groep.', max_length=255, null=True, populate_from='name', unique=True, verbose_name='Kort kenmerk'),
        ),
    ]
