# Generated by Django 5.2.6 on 2025-12-09 12:59

import django.core.validators
import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_alter_atlasgroup_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlasgroup',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='Een uniek kort kenmerk voor de groep.', max_length=255, null=True, populate_from='name', unique=True, validators=[django.core.validators.RegexValidator(message="Slugs mogen alleen letters, cijfers en koppeltekens ('-') bevatten.", regex='^[a-zA-Z0-9-]+$')], verbose_name='Kort kenmerk'),
        ),
    ]
