# Generated by Django 5.2.6 on 2025-12-17 13:18

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_alter_atlasgroup_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlasgroup',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='Een uniek kort kenmerk voor de groep.', max_length=255, null=True, populate_from='name', unique=True, verbose_name='Kort kenmerk'),
        ),
    ]
