# Generated by Django 5.2.9 on 2026-02-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0011_alter_atlasgroup_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlasgroup',
            name='external_id',
            field=models.CharField(blank=True, help_text='Het unieke kernmerk van de groep volgens de inlogbron. Alleen invullen als synchronisatie met inlogbron gewenst is.', max_length=255, null=True, verbose_name='External ID'),
        ),
    ]
