# Generated by Django 5.2.6 on 2025-12-08 19:20

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webservice', '0139_layer_related_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='De naam van de tabel', max_length=128, verbose_name='Naam')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, default=None, editable=False, help_text='Een uniek kort kenmerk voor de tabel in Atlas. Gebruik alleen kleine letters, cijfers en afbreekstreepjes.', max_length=255, null=True, populate_from='title', unique=True, verbose_name='Kort kenmerk')),
                ('source_type', models.CharField(choices=[('OWS', 'OWS'), ('WMTS', 'WMTS'), ('REST', 'REST')], default='OWS', verbose_name='Brontype')),
                ('fields', models.JSONField(blank=True, null=True)),
                ('list_endpoint', models.CharField(blank=True, max_length=1024, null=True, verbose_name='List endpoint')),
                ('detail_endpoint', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Detail endpoint')),
                ('list_cql_filters', models.JSONField(blank=True, null=True)),
                ('detail_cql_filters', models.JSONField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webservice.source')),
            ],
            options={
                'verbose_name': 'Tabel',
                'verbose_name_plural': 'Tabellen',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TableToTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_mapping', models.JSONField(verbose_name='Mapping van kolomnamen')),
                ('from_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_table_relations', to='tables_v2.tabletemp')),
                ('to_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_table_relations', to='tables_v2.tabletemp')),
            ],
            options={
                'unique_together': {('from_table', 'to_table')},
            },
        ),
        migrations.AddField(
            model_name='tabletemp',
            name='tables',
            field=models.ManyToManyField(related_name='related_tables', through='tables_v2.TableToTable', to='tables_v2.tabletemp'),
        ),
        migrations.CreateModel(
            name='LayerToTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_mapping', models.JSONField(verbose_name='Mapping van kolomnamen')),
                ('from_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_table_relations', to='webservice.layer')),
                ('to_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_table_relations', to='tables_v2.tabletemp')),
            ],
            options={
                'unique_together': {('from_layer', 'to_table')},
            },
        ),
    ]
