# Generated by Django 5.2.6 on 2025-12-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_v2', '0001_initial'),
        ('webservice', '0138_merge_20250911_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabletemp',
            name='layers',
            field=models.ManyToManyField(related_name='related_tables', through='tables_v2.LayerToTable', to='webservice.layer'),
        ),
    ]
