# Generated by Django 5.2.6 on 2025-12-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_v2', '0002_tabletemp_layers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabletemp',
            name='layer_name',
            field=models.CharField(help_text='De naam van de laag op de geoserver.', max_length=128, null=True, verbose_name='Laagnaam'),
        ),
    ]
