# Generated by Django 5.2.6 on 2025-12-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_v2', '0003_tabletemp_layer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabletemp',
            name='detail_display_properties',
            field=models.JSONField(blank=True, default=list, help_text='Lijst van kolomnamen die getoond worden in de detailweergave', null=True, verbose_name='Kolommen voor detailweergave'),
        ),
        migrations.AddField(
            model_name='tabletemp',
            name='list_display_properties',
            field=models.JSONField(blank=True, default=list, help_text='Lijst van kolomnamen die getoond worden in de lijstweergave', null=True, verbose_name='Kolommen voor lijstweergave'),
        ),
    ]
