# Generated by Django 5.2.6 on 2025-12-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_v2', '0004_tabletemp_detail_display_properties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabletemp',
            name='list_property',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Veldnaam van lijst'),
        ),
    ]
