# Generated by Django 5.2.6 on 2025-12-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_v2', '0005_tabletemp_list_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabletemp',
            name='items_per_page_property',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Veldnaam van items per pagina'),
        ),
        migrations.AddField(
            model_name='tabletemp',
            name='page_property',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Veldnaam van pagina'),
        ),
        migrations.AddField(
            model_name='tabletemp',
            name='total_items_page_property',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Veldnaam van totaal aantal items'),
        ),
    ]
