# Generated by Django 5.2.6 on 2025-12-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_v2', '0006_tabletemp_items_per_page_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabletemp',
            name='detail_property',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Veldnaam van detailweergave'),
        ),
    ]
