# Generated by Django 5.2.6 on 2025-12-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_v2', '0007_tabletemp_detail_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabletemp',
            name='items_per_page_property',
        ),
        migrations.RemoveField(
            model_name='tabletemp',
            name='page_property',
        ),
        migrations.AddField(
            model_name='tabletemp',
            name='items_per_page_param',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL parameter voor items per pagina'),
        ),
        migrations.AddField(
            model_name='tabletemp',
            name='page_param',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL parameter voor pagina'),
        ),
    ]
