# Generated by Django 5.2.6 on 2026-01-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_v2', '0008_remove_tabletemp_items_per_page_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabletemp',
            name='detail_error_property',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Veldnaam van foutmelding detailweergave'),
        ),
        migrations.AddField(
            model_name='tabletemp',
            name='list_error_property',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Veldnaam van foutmelding in lijstweergave'),
        ),
    ]
