# Generated by Django 5.2.6 on 2026-01-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_v2', '0009_tabletemp_detail_error_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabletemp',
            name='template_fields',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Templatevelden'),
        ),
    ]
