stages:
  - Test
  - Build
  - Deploy

variables:
  REVIEW_BASE_DOMAIN: delta10-review.nl
  FF_NETWORK_PER_BUILD: "true"

include:
  - ".gitlab/ci/test.yml"
  - ".gitlab/ci/build.yml"
  - ".gitlab/ci/deploy.yml"
