services:
  atlas:
    build:
      context: .
    environment:
      - DEBUG=False
      - SECRET_KEY=changemetosomethingsecret
      - ALLOWED_HOSTS=*
      - ADMIN_IPS=
      - INTERNAL_IPS=127.0.0.1
      - DB_HOST=postgres
      - DB_USER=atlas
      - DB_PASSWORD=atlas
      - DB_NAME=atlas
      - ENVIRONMENT=development
      - AUTHENTICATION_ENABLE_OIDC=True
      - AUTHENTICATION_ENABLE_CREDENTIALS=False
      - OIDC_ACTIVATE_ON_CREATE=True
      - OIDC_AUTHORIZATION_ENDPOINT=http://localhost:6556/auth
      - OIDC_TOKEN_ENDPOINT=http://dex:6556/token
      - OIDC_USER_ENDPOINT=http://dex:6556/userinfo
      - OIDC_JWKS_ENDPOINT=http://dex:6556/keys
      - SMARTSTREET_USER=
      - SMARTSTREET_PASSWORD=
      - SMARTSTREET_API_KEY=
      - GOOGLE_MAPS_API_KEY=
    ports:
      - 8000:8000
  postgres:
    image: postgres:15.12
    environment:
      - POSTGRES_USER=atlas
      - POSTGRES_PASSWORD=atlas
      - POSTGRES_DB=atlas
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  dex:
    image: quay.io/dexidp/dex:v2.28.1
    command: dex serve /config.yaml
    volumes:
      - ./dex.dev.yml:/config.yaml
    ports:
      - 6556:6556
  filter-proxy:
    image: ghcr.io/delta10/filter-proxy:0.7.3
    volumes:
      - ./filter-proxy.dev.yml:/config.yaml
    ports:
      - 8050:8050
  geoserver:
    image: ghcr.io/delta10/geoserver:2.25.5
    ports:
      - 8080:8080
    environment:
      - EXTRA_JAVA_OPTS=-Xms1G -Xmx2G
    volumes:
      - geoserver-data:/opt/geoserver_data
      - ./data/scholen.gpkg:/opt/geoserver_data/data/scholen.gpkg
volumes:
  postgres-data:
  geoserver-data:
