version: "3.7"
services:
  atlas:
    build:
      context: .
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CTRIX_IPS=${CTRIX_IPS}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - WFS_URL=${WFS_URL}
      - WFS_URL_CTRIX=${WFS_URL_CTRIX}
      - SMARTSTREET_USER=${SMARTSTREET_USER}
      - SMARTSTREET_PASSWORD=${SMARTSTREET_PASSWORD}
      - SMARTSTREET_API_KEY=${SMARTSTREET_API_KEY}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    ports:
      - 8000:8000
  postgres:
    image: postgres:15.1
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  dex:
    image: quay.io/dexidp/dex:v2.28.1
    command: dex serve /config.yaml
    volumes:
      - ./dex.dev.yml:/config.yaml
    ports:
      - 6556:6556

volumes:
  postgres-data:
