[project]
name = "Atlas"
version = "3.56.0"
requires-python = "==3.13.5"
dependencies = [
    "coverage==7.10.7",
    "django-constance==4.3.2",
    "django-debug-toolbar==6.0.0",
    "django-extensions==4.1",
    "django-filter==25.2",
    "django-import-export==4.4.0",
    "djangorestframework-simplejwt==5.5.1",
    "django-reversion==6.0.0",
    "Django==5.2.12",
    "djangorestframework==3.16.1",
    "mistune==3.2.0",
    "mozilla-django-oidc==4.0.1",
    "Pillow==12.0.0",
    "django-vite==3.1.0",
    "inertia-django-full-of-juice @ git+https://github.com/tinuvi/inertia-django-full-of-juice.git@main",
    "psycopg2-binary==2.9.11",
    "requests==2.32.5",
    "mkdocs-material==9.6.23",
    "django-revproxy==0.11.0",
]

[dependency-groups]
dev = [
    "commitizen==4.2.1",
    "ruff==0.13.3",
]
prod = [
    "uwsgi==2.0.31",
]
