apiVersion: v1
kind: Secret
metadata:
  name: {{ include "atlas.fullname" . }}
  labels:
    {{- include "atlas.labels" . | nindent 4 }}
type: Opaque
data:
  DEBUG: "{{ if .Values.https }}{{ "True" | b64enc }}{{ else }}{{ "False" | b64enc }}{{ end }}"
  SECRET_KEY: "{{ .Values.secretKey | b64enc }}"
  ALLOWED_HOSTS: "{{ .Values.allowedHosts | b64enc }}"
  CTRIX_IPS: "{{ .Values.ctrixIps | b64enc }}"
  DB_HOST: "{{ .Values.dbHost | b64enc }}"
  DB_USER: "{{ .Values.dbUser | b64enc }}"
  DB_PASSWORD: "{{ .Values.dbPassword | b64enc }}"
  DB_NAME: "{{ .Values.dbName | b64enc }}"
  WFS_URL: "{{ .Values.wfsUrl | b64enc }}"
  WFS_URL_CTRIX: "{{ .Values.wfsUrlCtrix | b64enc }}"
  SMARTSTREET_USER: "{{ .Values.smartstreetUser | b64enc }}"
  SMARTSTREET_PASSWORD: "{{ .Values.smartstreetPassword | b64enc }}"
  SMARTSTREET_API_KEY: "{{ .Values.smartstreetApiKey | b64enc }}"
  GOOGLE_MAPS_API_KEY: "{{ .Values.googleMapsApiKey | b64enc }}"
  SENTRY_DSN: "{{ .Values.sentryDsn | b64enc }}"
  MATOMO_URL: "{{ .Values.matomoUrl | b64enc }}"
  MATOMO_SITE_ID: "{{ .Values.matomoSiteId | b64enc }}"
