apiVersion: v1
kind: Secret
metadata:
  name: {{ include "atlas.fullname" . }}
  labels:
    {{- include "atlas.labels" . | nindent 4 }}
type: Opaque
data:
  DEBUG: "{{ if .Values.https }}{{ "True" | b64enc }}{{ else }}{{ "False" | b64enc }}{{ end }}"
  SECRET_KEY: "{{ .Values.secretKey | b64enc }}"
  ALLOWED_HOSTS: "{{ .Values.allowedHosts | b64enc }}"
  CTRIX_IPS: "{{ .Values.ctrixIps | b64enc }}"
  DB_HOST: "{{ .Values.dbHost | b64enc }}"
  DB_USER: "{{ .Values.dbUser | b64enc }}"
  DB_PASSWORD: "{{ .Values.dbPassword | b64enc }}"
  DB_NAME: "{{ .Values.dbName | b64enc }}"
  WFS_URL: "{{ .Values.wfsUrl | b64enc }}"
  WFS_URL_CTRIX: "{{ .Values.wfsUrlCtrix | b64enc }}"
  SMARTSTREET_USER: "{{ .Values.smartstreetUser | b64enc }}"
  SMARTSTREET_PASSWORD: "{{ .Values.smartstreetPassword | b64enc }}"
  SMARTSTREET_API_KEY: "{{ .Values.smartstreetApiKey | b64enc }}"
  GOOGLE_MAPS_API_KEY: "{{ .Values.googleMapsApiKey | b64enc }}"
  SENTRY_DSN: "{{ .Values.sentryDsn | b64enc }}"
  MATOMO_URL: "{{ .Values.matomoUrl | b64enc }}"
  MATOMO_SITE_ID: "{{ .Values.matomoSiteId | b64enc }}"
  AUTHENTICATION_ENABLE_CREDENTIALS: "{{ if .Values.authenticationEnableCredentials }}{{ "True" | b64enc }}{{ else }}{{ "False" | b64enc }}{{ end }}"
  AUTHENTICATION_ENABLE_OIDC: "{{ if .Values.authenticationEnableOidc }}{{ "True" | b64enc }}{{ else }}{{ "False" | b64enc }}{{ end }}"
  OIDC_CLIENT_ID: "{{ .Values.oidcClientId | b64enc }}"
  OIDC_CLIENT_SECRET: "{{ .Values.oidcClientSecret | b64enc }}"
  OIDC_SIGN_ALGO: "{{ .Values.oidcSignAlgo | b64enc }}"
  OIDC_SCOPES: "{{ .Values.oidcScopes | b64enc }}"
  OIDC_AUTHORIZATION_ENDPOINT: "{{ .Values.oidcAuthorizationEndpoint | b64enc }}"
  OIDC_TOKEN_ENDPOINT: "{{ .Values.oidcTokenEndpoint | b64enc }}"
  OIDC_USER_ENDPOINT: "{{ .Values.oidcUserEndpoint | b64enc }}"
  OIDC_JWKS_ENDPOINT: "{{ .Values.oidcJwksEndpoint | b64enc }}"
  OIDC_USERNAME_CLAIM: "{{ .Values.oidcUsernameClaim | b64enc }}"
  OIDC_ACTIVATE_ON_CREATE: "{{ if .Values.oidcActivateOnCreate }}{{ "True" | b64enc }}{{ else }}{{ "False" | b64enc }}{{ end }}"
