# Generated by Django 4.1.9 on 2023-09-20 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("webservice", "0095_source_atlas_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="Titel")),
                ("endpoint", models.CharField(max_length=500, verbose_name="Endpoint")),
                (
                    "list_fields",
                    models.TextField(
                        blank=True, null=True, verbose_name="Velden in lijstweergave"
                    ),
                ),
                (
                    "detail_fields",
                    models.TextField(
                        blank=True,
                        help_text="Voer één veld per regel in.",
                        null=True,
                        verbose_name="Velden in detailweergave",
                    ),
                ),
                (
                    "search_fields",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Velden waarop gezocht kan worden",
                    ),
                ),
                (
                    "friendly_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Maak veldnamen vriendelijk",
                        null=True,
                        verbose_name="Vriendelijke veldnamen",
                    ),
                ),
                (
                    "login_required",
                    models.BooleanField(
                        default=False,
                        help_text="De inhoud van deze dataset kan alleen bekeken worden door ingelogde gebruikers.",
                        verbose_name="Vereis inlog voor deze dataset",
                    ),
                ),
                (
                    "ordering",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Sortering"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webservice.source",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tabel",
                "verbose_name_plural": "Tabellen",
                "ordering": ["ordering", "title"],
            },
        ),
    ]
