# Generated by Django 4.1.9 on 2023-09-20 09:23

from django.db import migrations
import django.db.models.manager
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("tables", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="table",
            managers=[
                ("authorized", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="table",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                help_text="Een uniek kort kenmerk voor tabel.",
                populate_from="title",
                unique=True,
                verbose_name="Kort kenmerk",
            ),
        ),
    ]
