# Generated by Django 4.1.9 on 2023-09-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tables", "0002_alter_table_managers_table_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="method",
            field=models.CharField(
                choices=[("GET", "GET"), ("POST", "POST")],
                default="GET",
                max_length=20,
                verbose_name="Methode",
            ),
            preserve_default=False,
        ),
    ]
