# Generated by Django 4.1.9 on 2023-09-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tables", "0003_table_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="list_query",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Veldnaam van lijst"
            ),
        ),
    ]
