# Generated by Django 4.1.9 on 2023-09-20 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tables", "0004_table_list_query"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="detail_fields",
        ),
    ]
