# Generated by Django 4.1.9 on 2023-09-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tables", "0005_remove_table_detail_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="friendly_fields",
        ),
        migrations.AddField(
            model_name="table",
            name="list_header",
            field=models.TextField(
                blank=True,
                default=dict,
                help_text="Maak veldnamen vriendelijk",
                null=True,
                verbose_name="Vriendelijke veldnamen",
            ),
        ),
    ]
