# Generated by Django 4.1.9 on 2023-09-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tables", "0006_remove_table_friendly_fields_table_list_header"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="list_header",
        ),
        migrations.AddField(
            model_name="table",
            name="list_headings",
            field=models.TextField(
                blank=True, null=True, verbose_name="Kopjes in lijstweergave"
            ),
        ),
    ]
