# Generated by Django 4.1.9 on 2023-09-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tables", "0007_remove_table_list_header_table_list_headings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="login_required",
            field=models.BooleanField(
                default=False,
                help_text="De tabel is alleen zichtbaar voor ingelogde gebruikers.",
                verbose_name="Vereis inlog voor deze tabel",
            ),
        ),
    ]
