# Generated by Django 4.1.9 on 2023-10-07 12:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tables", "0008_alter_table_login_required"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="table",
            managers=[],
        ),
    ]
