# Generated by Django 4.1.9 on 2023-11-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tables", "0012_alter_table_search_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="error_field",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Veldnaam van foutmelding",
            ),
        ),
    ]
