# Generated by Django 4.1.9 on 2023-11-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tables", "0013_table_error_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="error_field",
        ),
        migrations.AddField(
            model_name="table",
            name="error_template",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Template van foutmelding",
            ),
        ),
    ]
