# Generated by Django 4.1.9 on 2023-12-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tables", "0014_remove_table_error_field_table_error_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="only_internal",
            field=models.BooleanField(
                default=True,
                help_text="Alleen zichtbaar binnen interne omgeving.",
                verbose_name="Alleen intern zichtbaar",
            ),
        ),
    ]
