# Generated by Django 4.1.13 on 2024-09-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0015_table_only_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='description',
            field=models.TextField(blank=True, help_text='Het is mogelijk om tekst op te maken met Markdown in dit veld', null=True, verbose_name='Beschrijving van de tabel'),
        ),
        migrations.AddField(
            model_name='table',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Selecteer een afbeelding om als thumbnail te gebruiken', null=True, upload_to='thumbnails/'),
        ),
    ]
