# Generated by Django 4.1.13 on 2025-03-11 14:01

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0016_table_description_table_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='Een uniek kort kenmerk voor tabel.', max_length=255, populate_from='title', unique=True, verbose_name='Kort kenmerk'),
        ),
    ]
