# Generated by Django 4.1.13 on 2025-03-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0017_alter_table_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='items_per_page_attribute',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Veldnaam van items per pagina'),
        ),
        migrations.AddField(
            model_name='table',
            name='page_attribute',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Veldnaam van pagina'),
        ),
        migrations.AddField(
            model_name='table',
            name='total_items_page_attribute',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Veldnaam van totaal aantal items'),
        ),
    ]
