# Generated by Django 5.2.6 on 2025-12-09 12:59

import django.core.validators
import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0018_table_items_per_page_attribute_table_page_attribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='Een uniek kort kenmerk voor tabel.', max_length=255, populate_from='title', unique=True, validators=[django.core.validators.RegexValidator(message="Slugs mogen alleen letters, cijfers en koppeltekens ('-') bevatten.", regex='^[a-zA-Z0-9-]+$')], verbose_name='Kort kenmerk'),
        ),
    ]
