# Generated by Django 2.1.4 on 2019-01-22 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20190115_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saveddataset',
            options={'ordering': ('-created_at', '-title')},
        ),
    ]
