# Generated by Django 4.0.1 on 2023-04-01 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_saveddataset_json'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedDataset',
        ),
    ]
