# Generated by Django 4.1.9 on 2023-07-31 18:00

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        help_text="Een uniek kort kenmerk.",
                        populate_from="title",
                        unique=True,
                        verbose_name="Kort kenmerk",
                    ),
                ),
                ("abstract", models.TextField(blank=True, null=True)),
                ("data_owner", models.CharField(max_length=256)),
                ("data_administrator", models.CharField(max_length=256)),
                ("contact_phone", models.CharField(max_length=256)),
                ("contact_address", models.CharField(max_length=256)),
                ("contact_email", models.CharField(max_length=256)),
                ("update_frequency", models.TextField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        help_text="Een uniek kort kenmerk.",
                        populate_from="title",
                        unique=True,
                        verbose_name="Kort kenmerk",
                    ),
                ),
            ],
        ),
    ]
