// DRAWING
const DEFAULT_DRAWING_COLOR = {
  red: 0,
  green: 102,
  blue: 255,
};

const DEFAULT_DRAWING_STROKE_WIDTH = 2;

const DEFAULT_DRAWING_FONT_SIZE = 22;

export { DEFAULT_DRAWING_FONT_SIZE, DEFAULT_DRAWING_STROKE_WIDTH, DEFAULT_DRAWING_COLOR };
