# Generated by Django 2.1.2 on 2018-11-27 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('js_type', models.CharField(default='themelayer:true',
                 help_text='javascript...', max_length=32, verbose_name='Javascript type')),
                ('closed_theme', models.BooleanField(
                    default=True, verbose_name='Gesloten thema')),
                ('the_order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Thema',
                'verbose_name_plural': "Thema's",
                'ordering': ['the_order'],
            },
        ),
        migrations.CreateModel(
            name='ThemeLayer',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_id', models.CharField(default='',
                 max_length=128, null=True, verbose_name='Layer_id')),
                ('title', models.CharField(
                    max_length=128, null=True, verbose_name='title')),
                ('layer_name', models.CharField(
                    max_length=128, null=True, verbose_name='layer_name')),
                ('meta_name', models.CharField(
                    max_length=128, null=True, verbose_name='meta_naam')),
                ('meta_kind', models.CharField(max_length=128,
                 null=True, verbose_name='meta_soort')),
                ('meta_org', models.CharField(
                    max_length=128, null=True, verbose_name='meta_org')),
                ('meta_updated', models.CharField(help_text='\nDe waarde wordt door javascript geëvalueerd("01-01-2018", getDate("year"))\'\n        ',
                 max_length=128, null=True, verbose_name='meta_bijgewerkt')),
                ('opacity', models.DecimalField(decimal_places=1,
                 default=0.9, max_digits=1, verbose_name='opacity')),
                ('visible', models.BooleanField(
                    default=False, verbose_name='visible')),
                ('isqueryable', models.BooleanField(
                    default=True, verbose_name='isqueryable')),
                ('_popup_attributes', models.CharField(blank=True,
                 max_length=250, null=True, verbose_name='popup attributes')),
                ('_search_fields', models.CharField(blank=True,
                 max_length=250, null=True, verbose_name='Zoek velden')),
                ('projection', models.CharField(default='EPSG:28992',
                 max_length=100, verbose_name='projection')),
                ('url', models.CharField(
                    default='https://datalab.purmerend.nl/geoserver/topp/wms?', max_length=500, verbose_name='url')),
                ('server_type', models.CharField(default='geoserver',
                 max_length=50, verbose_name='Server type')),
                ('closed_dataset', models.BooleanField(
                    default=True, verbose_name='Gesloten data')),
                ('published', models.BooleanField(
                    default=False, verbose_name='Gepubliceerd')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(
                    auto_now=True, verbose_name='updated_at')),
                ('atlas_groups', models.ManyToManyField(
                    blank=True, to='user_management.AtlasGroup')),
                ('layer_type', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, to='webservice.Theme')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                 related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(
                    blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thema kaart',
                'verbose_name_plural': 'Thema kaarten',
                'ordering': ['layer_type'],
            },
        ),
    ]
