# Generated by Django 2.1.4 on 2019-01-08 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0003_auto_20190108_1003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='themelayer',
            options={'ordering': ['ordering', 'title'], 'verbose_name': 'Thema kaart', 'verbose_name_plural': 'Thema kaarten'},
        ),
    ]
