# Generated by Django 2.1.4 on 2019-01-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0004_auto_20190108_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themelayer',
            name='meta_updated',
            field=models.CharField(help_text='\nDe waarde wordt door javascript geëvalueerd\n(Bijv: "01-01-2018", getDate("year"))\'\n        ',
                                   max_length=128, null=True, verbose_name='meta_bijgewerkt'),
        ),
    ]
