# Generated by Django 2.2 on 2019-04-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0005_auto_20190115_0810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Theme',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categorie', 'verbose_name_plural': 'Categorieën'},
        ),
        migrations.AlterModelOptions(
            name='themelayer',
            options={'ordering': ['ordering', 'title'], 'verbose_name': 'Kaartlaag', 'verbose_name_plural': 'Kaartlagen'},
        ),
    ]
