# Generated by Django 2.2 on 2019-11-29 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0012_auto_20191129_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='layer_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webservice.Category', verbose_name='Categorie'),
        ),
    ]
