# Generated by Django 2.2 on 2019-11-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0013_auto_20191129_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.AlterField(
            model_name='category',
            name='js_type',
            field=models.CharField(max_length=128, null=True, verbose_name='title'),
        ),
    ]
