# Generated by Django 2.2 on 2019-11-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0014_auto_20191129_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='js_type',
            new_name='title',
        ),
    ]
