# Generated by Django 2.2 on 2019-11-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0015_auto_20191129_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='js_type',
            field=models.CharField(default='themelayer:true', help_text='javascript...', max_length=128, verbose_name='Javascript type'),
        ),
    ]
