# Generated by Django 2.2.17 on 2021-01-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0019_additionaldata_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionaldata',
            options={'verbose_name': 'Additionele data', 'verbose_name_plural': 'Additionele data'},
        ),
        migrations.AddField(
            model_name='additionaldata',
            name='title',
            field=models.CharField(max_length=128, null=True, verbose_name='Titel'),
        ),
    ]
