# Generated by Django 2.2.17 on 2021-01-27 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0020_auto_20210127_2149'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdditionalData',
            new_name='LinkedData',
        ),
        migrations.AlterModelOptions(
            name='linkeddata',
            options={'verbose_name': 'Gekoppelde data', 'verbose_name_plural': 'Gekoppelde data'},
        ),
    ]
