# Generated by Django 2.2.17 on 2021-05-02 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0021_auto_20210127_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkeddata',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_data', to='webservice.Layer'),
        ),
    ]
