# Generated by Django 2.2.17 on 2021-05-12 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0021_auto_20210127_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='is_base',
            field=models.BooleanField(default=False, verbose_name='Is basislaag'),
        ),
        migrations.AddField(
            model_name='layer',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Is standaard zichtbaar'),
        ),
        migrations.AddField(
            model_name='layer',
            name='source_type',
            field=models.CharField(choices=[('WMS', 'WMS'), ('WMTS', 'WMTS')], default='WMS', max_length=20, verbose_name='Brontype'),
        ),
        migrations.AlterField(
            model_name='linkeddata',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_data', to='webservice.Layer'),
        ),
    ]
