# Generated by Django 2.2.24 on 2021-06-07 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0022_auto_20210512_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layer',
            options={'ordering': ['ordering', 'title'], 'verbose_name': 'Kaartlaag', 'verbose_name_plural': 'Kaartlagen'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='js_type',
        ),
        migrations.AlterField(
            model_name='category',
            name='ordering',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Sortering'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=128, null=True, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='_popup_attributes',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Toon deze velden'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='_search_fields',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Zoek in deze velden'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='atlas_groups',
            field=models.ManyToManyField(blank=True, to='user_management.AtlasGroup', verbose_name='Groepen'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='closed_dataset',
            field=models.BooleanField(default=True, help_text='Laag is alleen zichtbaar binnen interne omgeving', verbose_name='Besloten'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='isqueryable',
            field=models.BooleanField(default=True, verbose_name='Kan doorzocht worden'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='layer_id',
            field=models.CharField(default='', help_text='Het unieke kenmerk van de laag in Atlas', max_length=128, null=True, verbose_name='Laag ID'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='layer_name',
            field=models.CharField(help_text='De naam van de laag op de geoserver', max_length=128, null=True, verbose_name='Laagnaam'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='meta_kind',
            field=models.CharField(max_length=128, null=True, verbose_name='Soort'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='meta_name',
            field=models.CharField(max_length=128, null=True, verbose_name='Naam'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='meta_org',
            field=models.CharField(max_length=128, null=True, verbose_name='Organisatie'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='meta_updated',
            field=models.CharField(max_length=128, null=True, verbose_name='Laatst bijgewerkt'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='not_in_atlas',
            field=models.BooleanField(default=False, help_text='De laag wordt niet getoond in de standaardkaart', verbose_name='Toon laag alleen in een themakaart'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='opacity',
            field=models.DecimalField(decimal_places=1, default=0.9, max_digits=1, verbose_name='Ondoorzichtigheid'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='ordering',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Sortering'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Eigenaar'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='projection',
            field=models.CharField(default='EPSG:28992', max_length=100, verbose_name='Projectie'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='server_type',
            field=models.CharField(default='geoserver', max_length=50, verbose_name='Servertype'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='title',
            field=models.CharField(max_length=128, null=True, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='url',
            field=models.CharField(default='https://datalab.purmerend.nl/geoserver/topp/wms?', max_length=500, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Gebruikers'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='Zichtbaar'),
        ),
    ]
