# Generated by Django 2.2.17 on 2021-05-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0022_auto_20210502_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='source_type',
            field=models.CharField(max_length=128, null=True, verbose_name='source_type'),
        ),
    ]
