# Generated by Django 2.2.17 on 2021-05-02 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0023_layer_source_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='source_type',
        ),
    ]
