# Generated by Django 2.2.24 on 2021-06-10 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0023_auto_20210607_1431'),
        ('webservice', '0023_auto_20210607_2013'),
    ]

    operations = [
    ]
