# Generated by Django 2.2.24 on 2021-06-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0024_merge_20210610_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='source_type',
            field=models.CharField(choices=[('WMS_WFS', 'WMS en WFS'), ('WMS', 'WMS'), ('WMTS', 'WMTS')], default='WMS_WFS',
                                   help_text='"WMS en WFS" is zichtbaar in zowel het datapaneel als op de kaart. WMS en WMTS toont alleen op de kaart.', max_length=20, verbose_name='Brontype'),
        ),
    ]
