# Generated by Django 2.2.17 on 2021-05-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0024_remove_layer_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='source_type',
            field=models.CharField(default='wms', max_length=128, null=True, verbose_name='source_type'),
        ),
    ]
