# Generated by Django 2.2.24 on 2021-06-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0025_auto_20210610_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkeddata',
            name='popup_attributes',
            field=models.CharField(blank=True, help_text='Voer één veld per regel in. Bij een leeg veld worden alle velden getoond.',
                                   max_length=250, null=True, verbose_name='Toon deze velden'),
        ),
    ]
