# Generated by Django 2.2.24 on 2021-06-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0027_remove_category_closed_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='isqueryable',
            field=models.BooleanField(
                default=True, help_text='Deze instelling is alleen van toepassing op Atlas versie 2 en wordt binnenkort verwijderd', verbose_name='Kan doorzocht worden'),
        ),
    ]
