# Generated by Django 2.2.24 on 2021-06-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0028_auto_20210610_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlastheme',
            name='title',
            field=models.CharField(max_length=128, null=True, verbose_name='Titel'),
        ),
    ]
