# Generated by Django 2.2.24 on 2021-07-21 10:00

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0030_auto_20210623_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlastheme',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, help_text='Een uniek kort kenmerk voor het thema in Atlas. Dit kenmerk komt terug in links naar de laag.', populate_from='title', verbose_name='Kort kenmerk'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='closed_dataset',
            field=models.BooleanField(
                default=True, help_text='Laag is alleen zichtbaar binnen interne omgeving.', verbose_name='Besloten'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='layer_id',
            field=models.CharField(default='', help_text='Een uniek kenmerk voor de laag in Atlas. Dit kenmerk komt terug in links naar de laag.',
                                   max_length=128, null=True, verbose_name='Kort kenmerk'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='layer_name',
            field=models.CharField(help_text='De naam van de laag op de geoserver.',
                                   max_length=128, null=True, verbose_name='Laagnaam'),
        ),
    ]
