# Generated by Django 2.2.24 on 2021-07-06 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0030_auto_20210623_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ATTRIBUTE', 'Veld'), ('TIME', 'Tijd')], default='ATTRIBUTE', max_length=20, verbose_name='Filtertype')),
                ('field', models.CharField(max_length=128, verbose_name='Veld')),
                ('values', models.CharField(max_length=128, verbose_name='Veld')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='webservice.Layer')),
            ],
        ),
    ]
