# Generated by Django 2.2.24 on 2021-07-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0030_auto_20210623_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='meta_kind',
            field=models.CharField(help_text='Het is mogelijk om tekst op te maken met Markdown in dit veld',
                                   max_length=128, null=True, verbose_name='Soort'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='meta_org',
            field=models.CharField(help_text='Het is mogelijk om tekst op te maken met Markdown in dit veld',
                                   max_length=128, null=True, verbose_name='Organisatie'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='meta_updated',
            field=models.CharField(help_text='Het is mogelijk om tekst op te maken met Markdown in dit veld',
                                   max_length=128, null=True, verbose_name='Laatst bijgewerkt'),
        ),
    ]
