# Generated by Django 2.2.24 on 2021-07-21 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0031_auto_20210721_1200'),
        ('webservice', '0031_auto_20210721_1258'),
    ]

    operations = [
    ]
