# Generated by Django 2.2.24 on 2021-07-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0031_filter'),
        ('webservice', '0032_merge_20210721_1555'),
    ]

    operations = [
    ]
