# Generated by Django 2.2.24 on 2021-07-22 13:53

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0032_merge_20210721_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlastheme',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, help_text='Een uniek kort kenmerk voor het thema in Atlas. Dit kenmerk komt terug in links naar het thema.', populate_from='title', verbose_name='Kort kenmerk'),
        ),
    ]
