# Generated by Django 2.2.24 on 2021-08-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0033_auto_20210722_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='_popup_attributes',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Toon deze velden'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='_search_fields',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Zoek in deze velden'),
        ),
    ]
