# Generated by Django 2.2.24 on 2021-07-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0033_merge_20210722_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='name',
            field=models.CharField(default='', max_length=128, verbose_name='Naam'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filter',
            name='kind',
            field=models.CharField(choices=[('ATTRIBUTE', 'Veld')], default='ATTRIBUTE', max_length=20, verbose_name='Filtertype'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='values',
            field=models.CharField(max_length=128, verbose_name='Waarden'),
        ),
    ]
