# Generated by Django 2.2.24 on 2021-07-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0034_auto_20210722_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='name',
        ),
        migrations.AddField(
            model_name='filter',
            name='title',
            field=models.CharField(default='', max_length=128, verbose_name='Titel'),
            preserve_default=False,
        ),
    ]
