# Generated by Django 3.2.7 on 2021-09-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0034_auto_20210818_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='extent_max_x',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='extent_max_y',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='extent_min_x',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='extent_min_y',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='zoom_max',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='zoom_min',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
