# Generated by Django 2.2.24 on 2021-07-22 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0035_auto_20210722_1546'),
        ('webservice', '0033_auto_20210722_1553'),
    ]

    operations = [
    ]
