# Generated by Django 3.2.7 on 2021-10-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0035_auto_20210929_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='extent_max_x',
            field=models.FloatField(
                blank=True, default=None, null=True, verbose_name='Bereik maximum x'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='extent_max_y',
            field=models.FloatField(
                blank=True, default=None, null=True, verbose_name='Bereik maximum y'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='extent_min_x',
            field=models.FloatField(
                blank=True, default=None, help_text='Vul in om de laag inactief te maken wanneer de weergave buiten het bereik ligt.', null=True, verbose_name='Bereik minimum x'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='extent_min_y',
            field=models.FloatField(
                blank=True, default=None, null=True, verbose_name='Bereik minimum y'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='zoom_max',
            field=models.IntegerField(
                blank=True, default=None, null=True, verbose_name='Zoomniveau maximum'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='zoom_min',
            field=models.IntegerField(
                blank=True, default=None, help_text='Vul in om de laag inactief te maken wanneer de weergave buiten het zoomniveau ligt.', null=True, verbose_name='Zoomniveau minimum'),
        ),
    ]
