# Generated by Django 3.2.7 on 2021-10-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0036_auto_20211014_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='style',
            field=models.JSONField(default={}, help_text='Stijl voor een WFS laag in GeoStyler formaat', verbose_name='Stijl'),
        ),
    ]
