# Generated by Django 3.2.7 on 2021-10-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0037_layer_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='style',
            field=models.JSONField(default=dict, help_text='Stijl voor een WFS laag in GeoStyler formaat', verbose_name='Stijl'),
        ),
    ]
