# Generated by Django 3.2.7 on 2021-10-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0040_alter_layer_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='style',
            field=models.JSONField(blank=True, default=dict, help_text='Stijl voor een WFS laag in GeoStyler formaat', null=True, verbose_name='Stijl'),
        ),
    ]
