# Generated by Django 3.2.7 on 2021-11-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0041_alter_layer_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='login_required',
            field=models.BooleanField(default=False, help_text='Voor deze dataset is een inlog vereist.', verbose_name='Vereis inlog voor deze dataset'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='closed_dataset',
            field=models.BooleanField(default=True, help_text='Laag is alleen zichtbaar binnen interne omgeving.', verbose_name='Alleen intern zichtbaar'),
        ),
    ]
