# Generated by Django 3.2.7 on 2021-11-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0042_auto_20211118_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='ckan_url',
            field=models.URLField(blank=True, help_text='Haal metadata op via CKAN', null=True, verbose_name='CKAN metadata URL'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='meta_kind',
            field=models.CharField(blank=True, help_text='Het is mogelijk om tekst op te maken met Markdown in dit veld', max_length=128, null=True, verbose_name='Soort'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='meta_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Naam'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='meta_org',
            field=models.CharField(blank=True, help_text='Het is mogelijk om tekst op te maken met Markdown in dit veld', max_length=128, null=True, verbose_name='Organisatie'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='meta_updated',
            field=models.CharField(blank=True, help_text='Het is mogelijk om tekst op te maken met Markdown in dit veld', max_length=128, null=True, verbose_name='Laatst bijgewerkt'),
        ),
    ]
