# Generated by Django 3.2.10 on 2022-01-04 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0043_viewer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewer',
            options={'ordering': ['ordering', 'label'], 'verbose_name': 'Viewer', 'verbose_name_plural': 'Viewers'},
        ),
    ]
