# Generated by Django 3.2.10 on 2022-01-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0044_alter_viewer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='url',
            field=models.CharField(max_length=500, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='linkeddata',
            name='url',
            field=models.CharField(max_length=500, verbose_name='URL'),
        ),
    ]
