# Generated by Django 3.2.10 on 2022-01-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0045_auto_20220119_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='source_type',
            field=models.CharField(choices=[('WMS_WFS', 'WMS en WFS'), ('WMS', 'WMS'), ('WFS', 'WFS'), ('WMTS', 'WMTS'), ('XYZ', 'XYZ'), ('MVT', 'MVT')], default='WMS_WFS',
                                   help_text='"WMS en WFS" en WFS is zichtbaar in zowel het datapaneel als op de kaart. WMS en WMTS toont alleen op de kaart.', max_length=20, verbose_name='Brontype'),
        ),
    ]
