# Generated by Django 3.2.10 on 2022-02-03 11:29

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0047_rename_atlastheme_map'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map',
            options={'verbose_name': 'Kaart',
                     'verbose_name_plural': 'Kaarten'},
        ),
        migrations.AlterField(
            model_name='map',
            name='layers',
            field=models.ManyToManyField(
                to='webservice.Layer', verbose_name='Lagen'),
        ),
        migrations.AlterField(
            model_name='map',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, help_text='Een uniek kort kenmerk voor de kaart in Atlas. Dit kenmerk komt terug in links naar het thema.', populate_from='title', verbose_name='Kort kenmerk'),
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(
                    max_length=128, null=True, verbose_name='Titel')),
                ('layers', models.ManyToManyField(
                    to='webservice.Layer', verbose_name='Lagen')),
            ],
            options={
                'verbose_name': 'Thema',
                'verbose_name_plural': "Thema's",
            },
        ),
    ]
