# Generated by Django 3.2.10 on 2022-02-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0048_auto_20220203_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='ordering',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Sortering'),
        ),
    ]
