# Generated by Django 3.2.10 on 2022-02-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0049_theme_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='icon',
            field=models.FileField(blank=True, upload_to='theme_icons/'),
        ),
    ]
