# Generated by Django 3.2.10 on 2022-02-03 12:16

from django.db import migrations, models
import webservice.models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0050_theme_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, null=True, verbose_name='Titel')),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['ordering', 'title'], 'verbose_name': 'Thema', 'verbose_name_plural': "Thema's"},
        ),
        migrations.AlterField(
            model_name='theme',
            name='icon',
            field=models.FileField(blank=True, upload_to='theme_icons/', validators=[webservice.models.validate_file_extension]),
        ),
    ]
