# Generated by Django 3.2.10 on 2022-02-03 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0051_auto_20220203_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name': 'Bron', 'verbose_name_plural': 'Bronnen'},
        ),
        migrations.AddField(
            model_name='layer',
            name='layer_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webservice.source', verbose_name='Bron'),
        ),
    ]
