# Generated by Django 3.2.10 on 2022-02-03 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0052_auto_20220203_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='layer_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webservice.source', verbose_name='Bron'),
        ),
    ]
