# Generated by Django 3.2.10 on 2022-02-03 12:25

from django.db import migrations


def move_urls_to_source(apps, _):
    Layer = apps.get_model('webservice', 'Layer')
    Source = apps.get_model('webservice', 'Source')

    url_to_source = {}

    for source in Source.objects.all():
        url_to_source[source.url] = source

    for layer in Layer.objects.all():
        if layer.url not in url_to_source:
            source = Source.objects.create(
                title=layer.url[:128], url=layer.url)
            url_to_source[layer.url] = source

        layer.layer_source = url_to_source[layer.url]
        layer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0053_alter_layer_layer_source'),
    ]

    operations = [
        migrations.RunPython(move_urls_to_source, migrations.RunPython.noop),
    ]
