# Generated by Django 3.2.10 on 2022-02-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0055_remove_layer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='features',
            field=models.JSONField(blank=True, default=dict, verbose_name='Functies'),
        ),
    ]
