# Generated by Django 3.2.10 on 2022-03-16 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0056_map_features'),
        ('webservice', '0057_alter_layer_opacity'),
    ]

    operations = [
    ]
