# Generated by Django 3.2.10 on 2022-04-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0058_merge_0056_map_features_0057_alter_layer_opacity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map',
            options={'ordering': ['title'], 'verbose_name': 'Kaart', 'verbose_name_plural': 'Kaarten'},
        ),
        migrations.AlterField(
            model_name='map',
            name='layers',
            field=models.ManyToManyField(blank=True, to='webservice.Layer', verbose_name='Lagen'),
        ),
    ]
