# Generated by Django 3.2.10 on 2022-04-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0058_merge_0056_map_features_0057_alter_layer_opacity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map',
            options={'ordering': [
                'title'], 'verbose_name': 'Kaart', 'verbose_name_plural': 'Kaarten'},
        ),
        migrations.AlterField(
            model_name='viewer',
            name='internal',
            field=models.BooleanField(
                default=True, help_text='Is alleen zichtbaar binnen interne omgeving. Hou er rekening mee dat de gebruikernaam, het wachtwoord of de API key gedeeld wordt met het publieke internet op het moment dat deze optie uit staat.', verbose_name='Alleen intern zichtbaar'),
        ),
    ]
