# Generated by Django 3.2.13 on 2022-04-14 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0059_auto_20220410_1208'),
        ('webservice', '0059_auto_20220414_0946'),
    ]

    operations = [
    ]
