# Generated by Django 3.2.13 on 2022-04-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0060_merge_0059_auto_20220410_1208_0059_auto_20220414_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='settings',
            field=models.JSONField(blank=True, default=dict, verbose_name='Instellingen'),
        ),
    ]
