# Generated by Django 3.2.13 on 2022-05-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0060_merge_0059_auto_20220410_1208_0059_auto_20220414_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='format',
            field=models.CharField(choices=[('image/png', 'image/png'), ('image/jpeg', 'image/jpeg')],
                                   default='image/png', max_length=128, verbose_name='Formaat'),
        ),
    ]
