# Generated by Django 3.2.13 on 2022-05-12 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0061_map_settings'),
        ('webservice', '0064_alter_layer_format'),
    ]

    operations = [
    ]
