# Generated by Django 3.2.13 on 2022-09-04 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0065_merge_0061_map_settings_0064_alter_layer_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(
                    max_length=500, verbose_name='Endpoint')),
                ('title', models.CharField(max_length=128, verbose_name='Titel')),
                ('list', models.CharField(blank=True, max_length=128,
                 null=True, verbose_name='Veld met lijst')),
                ('headers', models.TextField(blank=True, help_text='Voer één veld per regel in. Bij een leeg veld worden alle velden getoond.',
                 max_length=128, null=True, verbose_name='Kopjes')),
                ('fields', models.TextField(
                    blank=True, help_text='Voer één veld per regel in. Bij een leeg veld worden alle velden getoond.', null=True, verbose_name='Velden')),
                ('ordering', models.PositiveIntegerField(
                    db_index=True, default=0, verbose_name='Sortering')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='templates', to='webservice.layer')),
                ('source', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='webservice.source')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ['ordering'],
            },
        ),
    ]
