# Generated by Django 3.2.13 on 2022-05-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0065_merge_0061_map_settings_0064_alter_layer_format'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkeddata',
            old_name='source',
            new_name='parent',
        ),
    ]
