# Generated by Django 3.2.13 on 2022-09-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0066_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='fields',
            field=models.TextField(blank=True, help_text='Voer één veld per regel in.', null=True, verbose_name='Velden'),
        ),
        migrations.AlterField(
            model_name='template',
            name='headers',
            field=models.TextField(blank=True, help_text='Voer één veld per regel in.', max_length=128, null=True, verbose_name='Kopjes'),
        ),
    ]
