# Generated by Django 3.2.13 on 2022-05-19 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0066_rename_source_linkeddata_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkeddata',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_data', to='webservice.source'),
        ),
        migrations.AlterField(
            model_name='linkeddata',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='webservice.layer'),
        ),
    ]
