# Generated by Django 3.2.13 on 2022-07-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0066_rename_source_linkeddata_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkeddata',
            name='source',
            field=models.CharField(choices=[('WFS', 'WFS'), ('REST', 'REST')], default='WFS', max_length=10),
            preserve_default=False,
        ),
    ]
