# Generated by Django 3.2.13 on 2022-07-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0067_linkeddata_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkeddata',
            name='templates',
            field=models.JSONField(blank=True, default=dict, verbose_name='Templates'),
        ),
    ]
