# Generated by Django 3.2.13 on 2022-09-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0067_auto_20220904_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='template',
            field=models.TextField(blank=True, null=True, verbose_name='Template'),
        ),
    ]
