# Generated by Django 3.2.13 on 2022-05-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0067_auto_20220519_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='authentication',
            field=models.BooleanField(default=False),
        ),
    ]
