# Generated by Django 3.2.13 on 2022-05-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0068_source_authentication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='authentication',
        ),
        migrations.AddField(
            model_name='source',
            name='allow_authentication',
            field=models.BooleanField(default=False, verbose_name='Sta authenticatie toe'),
        ),
    ]
