# Generated by Django 3.2.13 on 2022-05-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0069_auto_20220519_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('GEO', 'Geo'), ('REST', 'REST')], default='GEO', max_length=25),
        ),
    ]
