# Generated by Django 3.2.13 on 2022-09-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0070_alter_template_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='_popup_attributes',
            field=models.CharField(blank=True, max_length=500, null=True,
                                   verbose_name='Voer één veld per regel in. Bij geen invoer worden alle velden getoond'),
        ),
    ]
