# Generated by Django 3.2.13 on 2022-05-19 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0070_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkeddata',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_data', to='webservice.layer'),
        ),
    ]
