# Generated by Django 3.2.13 on 2022-10-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0071_alter_layer__popup_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkeddata',
            name='popup_attributes',
            field=models.CharField(blank=True, help_text='Voer één veld per regel in. Bij geen invoer worden alle velden getoond.',
                                   max_length=250, null=True, verbose_name='Toon deze velden'),
        ),
    ]
