# Generated by Django 3.2.13 on 2022-10-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0071_alter_layer__popup_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='authenticate',
            field=models.BooleanField(default=False, help_text='Configureer dit alleen voor vertrouwde bronnen', verbose_name='Authenticeer op bron'),
        ),
    ]
