# Generated by Django 3.2.13 on 2022-10-13 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0072_alter_linkeddata_popup_attributes'),
        ('webservice', '0073_alter_source_authenticate'),
    ]

    operations = [
    ]
