# Generated by Django 3.2.13 on 2022-11-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0074_merge_20221013_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layer',
            old_name='meta_kind',
            new_name='meta_description'
        ),
        migrations.AlterField(
            model_name='layer',
            name='meta_description',
            field=models.CharField(help_text='Het is mogelijk om tekst op te maken met Markdown in dit veld',
                                   max_length=128, null=True, verbose_name='Omschrijving'),
        ),
    ]
