# Generated by Django 3.2.13 on 2022-11-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0075_auto_20221122_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='meta_description',
            field=models.TextField(help_text='Het is mogelijk om tekst op te maken met Markdown in dit veld', null=True, verbose_name='Omschrijving'),
        ),
    ]
