# Generated by Django 3.2.13 on 2022-11-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0076_alter_layer_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='meta_link',
            field=models.URLField(help_text='Link naar beschrijving in metadatacatalogus', null=True, verbose_name='Meer informatie'),
        ),
    ]
