# Generated by Django 3.2.13 on 2022-11-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0077_layer_meta_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='meta_link',
            field=models.URLField(blank=True, help_text='Link naar beschrijving in metadatacatalogus', null=True, verbose_name='Meer informatie'),
        ),
    ]
