# Generated by Django 4.0.1 on 2023-04-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0078_alter_layer_meta_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='meta_link',
            field=models.URLField(blank=True, help_text='Link naar metadatacatalogus met meer informatie', null=True, verbose_name='Meer informatie'),
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
