# Generated by Django 4.0.1 on 2023-04-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0079_alter_layer_meta_link_delete_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='friendly_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Maak veldnamen vriendelijk', null=True, verbose_name='Vriendelijke veldnamen'),
        ),
    ]
