# Generated by Django 4.0.1 on 2023-04-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0081_remove_layer_isqueryable'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='show_in_detail_panel',
            field=models.BooleanField(default=True, verbose_name='Toon in detail- en dataweergave'),
        ),
    ]
