# Generated by Django 4.0.1 on 2023-04-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0082_layer_show_in_detail_panel'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='is_selectable',
            field=models.BooleanField(default=True, verbose_name='Is selecteerbaar'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='show_in_detail_panel',
            field=models.BooleanField(default=True, verbose_name='Toon laag in detail- en dataweergave'),
        ),
    ]
