# Generated by Django 4.1.9 on 2023-07-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webservice", "0085_alter_layer_opacity"),
    ]

    operations = [
        migrations.RenameField(
            model_name='layer',
            old_name='style',
            new_name='client_style'
        ),
        migrations.AddField(
            model_name="layer",
            name="server_style",
            field=models.CharField(
                blank=True,
                help_text="Stijlnaam zoals beschikbaar op de server",
                max_length=128,
                null=True,
                verbose_name="Stijlnaam voor WMS / WMTS laag",
            ),
        ),
    ]
