# Generated by Django 4.1.9 on 2023-08-31 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webservice", "0090_alter_source_options_alter_viewer_internal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="layer",
            name="users",
        ),
    ]
