# Generated by Django 4.1.9 on 2023-08-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0004_alter_atlasuser_first_name"),
        ("webservice", "0091_remove_layer_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layer",
            name="atlas_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="De inhoud van deze dataset kan alleen bekeken worden als de gebruiker lid is van een van deze groepen.",
                to="user_management.atlasgroup",
                verbose_name="Groepen",
            ),
        ),
        migrations.AlterField(
            model_name="layer",
            name="login_required",
            field=models.BooleanField(
                default=False,
                help_text="De inhoud van deze dataset kan alleen bekeken worden door ingelogde gebruikers.",
                verbose_name="Vereis inlog voor deze dataset",
            ),
        ),
    ]
