# Generated by Django 4.1.9 on 2023-09-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webservice", "0092_alter_layer_atlas_groups_alter_layer_login_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="source_type",
            field=models.CharField(
                choices=[("OWS", "OWS"), ("WMTS", "WMTS"), ("REST", "REST")],
                default="OWS",
                help_text="Selecteer het type bron",
                max_length=20,
                verbose_name="Brontype",
            ),
        ),
    ]
