# Generated by Django 4.1.9 on 2023-09-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webservice", "0092_alter_layer_atlas_groups_alter_layer_login_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="tooltip",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="layer",
            name="format",
            field=models.CharField(
                choices=[
                    ("image/png", "image/png"),
                    ("image/jpeg", "image/jpeg"),
                    ("image/vnd.jpeg-png", "image/vnd.jpeg-png"),
                    (
                        "application/vnd.mapbox-vector-tile",
                        "application/vnd.mapbox-vector-tile",
                    ),
                ],
                default="image/png",
                max_length=128,
                verbose_name="Formaat",
            ),
        ),
    ]
