# Generated by Django 4.1.9 on 2023-09-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webservice", "0093_source_source_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="login_required",
            field=models.BooleanField(
                default=False,
                help_text="De inhoud van deze bron kan alleen bekeken worden door ingelogde gebruikers.",
                verbose_name="Vereis inlog voor deze bron",
            ),
        ),
    ]
