# Generated by Django 4.1.9 on 2023-10-07 12:53

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("webservice", "0095_source_atlas_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="Selection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=128, null=True, verbose_name="Titel"),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        help_text="Een uniek kort kenmerk voor de kaartselectie in Atlas.",
                        populate_from="title",
                        unique=True,
                        verbose_name="Kort kenmerk",
                    ),
                ),
                (
                    "layers",
                    models.ManyToManyField(
                        blank=True, to="webservice.layer", verbose_name="Lagen"
                    ),
                ),
            ],
        ),
    ]
