# Generated by Django 4.1.9 on 2023-10-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webservice", "0096_selection"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="selection",
            options={"verbose_name": "Selectie", "verbose_name_plural": "Selecties"},
        ),
        migrations.AddField(
            model_name="selection",
            name="login_required",
            field=models.BooleanField(
                default=False,
                help_text="De selectie kan alleen bekeken worden door ingelogde gebruikers.",
                verbose_name="Vereis inlog voor deze selectie",
            ),
        ),
    ]
