# Generated by Django 4.1.9 on 2023-10-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webservice", "0097_alter_selection_options_selection_login_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="map",
            name="login_required",
            field=models.BooleanField(
                default=False,
                help_text="De inhoud van deze kaart kan alleen bekeken worden door ingelogde gebruikers.",
                verbose_name="Vereis inlog voor deze kaart",
            ),
        ),
    ]
