# Generated by Django 4.1.9 on 2023-10-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webservice", "0098_map_login_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="viewer",
            name="type",
            field=models.CharField(
                choices=[
                    ("GOOGLE_MAPS", "Google Maps"),
                    ("STREET_SMART", "Street Smart"),
                    ("OBLIQUO", "Obliquo"),
                    ("IFRAME", "Iframe"),
                    ("BUTTON", "Knop naar nieuw tabblad"),
                ],
                default="GOOGLE_MAPS",
                max_length=20,
                verbose_name="Type",
            ),
        ),
    ]
