# Generated by Django 4.1.9 on 2023-11-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webservice", "0100_alter_layer_options_layer_templated_fields_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="meta_contact",
            field=models.TextField(
                blank=True, null=True, verbose_name="Contactpersoon"
            ),
        ),
        migrations.AddField(
            model_name="layer",
            name="meta_lineage",
            field=models.TextField(
                blank=True,
                help_text="Beschrijft de herkomst van de dataset",
                null=True,
                verbose_name="Bron",
            ),
        ),
        migrations.AlterField(
            model_name="layer",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="Het is mogelijk om tekst op te maken met Markdown in dit veld",
                null=True,
                verbose_name="Omschrijving",
            ),
        ),
        migrations.AlterField(
            model_name="layer",
            name="meta_name",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Naam"
            ),
        ),
        migrations.AlterField(
            model_name="layer",
            name="meta_org",
            field=models.CharField(
                blank=True,
                help_text="Het is mogelijk om tekst op te maken met Markdown in dit veld",
                max_length=128,
                null=True,
                verbose_name="Organisatie",
            ),
        ),
        migrations.AlterField(
            model_name="layer",
            name="meta_updated",
            field=models.CharField(
                blank=True,
                help_text="Het is mogelijk om tekst op te maken met Markdown in dit veld",
                max_length=128,
                null=True,
                verbose_name="Laatst bijgewerkt",
            ),
        )
    ]
