# Generated by Django 4.1.9 on 2023-11-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webservice", "0102_alter_category_slug_alter_layer_meta_lineage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layer",
            name="meta_contact",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Contactpersoon"
            ),
        )
    ]
