# Generated by Django 4.1.9 on 2023-11-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webservice", "0103_alter_category_slug_alter_layer_meta_contact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="viewer",
            name="is_oblique",
            field=models.BooleanField(blank=True, default=False),
        )
    ]
