# Generated by Django 4.1.13 on 2024-01-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webservice", "0103_alter_category_slug_alter_layer_meta_contact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layer",
            name="_popup_attributes",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Voer één veld per regel in. Bij geen invoer worden alle velden getoond",
            ),
        ),
        migrations.AlterField(
            model_name="linkeddata",
            name="popup_attributes",
            field=models.TextField(
                blank=True,
                help_text="Voer één veld per regel in. Bij geen invoer worden alle velden getoond.",
                null=True,
                verbose_name="Toon deze velden",
            ),
        ),
    ]
