# Generated by Django 4.1.9 on 2023-11-17 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webservice", "0104_viewer_is_oblique_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkeddata",
            name="headers",
            field=models.TextField(
                blank=True,
                help_text="Voer één veld per regel in.",
                max_length=128,
                null=True,
                verbose_name="Tabel kopjes",
            ),
        ),
    ]
