# Generated by Django 4.1.9 on 2023-11-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webservice", "0105_linkeddata_headers_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linkeddata",
            name="popup_attributes",
            field=models.CharField(
                blank=True,
                help_text="Voer één veld per regel in. Bij geen invoer worden alle velden getoond.",
                max_length=250,
                null=True,
                verbose_name="Tabel velden",
            ),
        ),
    ]
