# Generated by Django 4.1.9 on 2023-11-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webservice", "0106_alter_category_slug_alter_layer_slug_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("source", models.CharField(max_length=255)),
                ("resources", models.CharField(max_length=255)),
                ("params", models.JSONField()),
                ("time_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
