# Generated by Django 4.1.9 on 2023-12-10 17:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webservice", "0107_log_alter_category_slug_alter_layer_slug"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Log",
        ),
    ]
