# Generated by Django 4.1.9 on 2023-12-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webservice", "0108_delete_log_alter_category_slug_alter_layer_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="legend_url",
            field=models.URLField(
                blank=True,
                help_text="Overschrijf link naar legenda",
                null=True,
                verbose_name="Legenda",
            ),
        ),
    ]
