# Generated by Django 4.1.9 on 2024-01-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webservice", "0109_layer_legend_url_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="method",
            field=models.CharField(
                choices=[("GET", "GET"), ("POST", "POST")],
                default="GET",
                max_length=20,
                verbose_name="Methode",
            ),
        )
    ]
