# Generated by Django 4.1.13 on 2024-02-08 08:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "webservice",
            "0104_alter_category_slug_alter_layer__popup_attributes_and_more",
        ),
        ("webservice", "0110_template_method_alter_category_slug_alter_layer_slug"),
    ]

    operations = []
