# Generated by Django 4.1.13 on 2024-02-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webservice", "0111_merge_20240208_0949"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="use_html_info_format",
            field=models.BooleanField(
                default=False, verbose_name="Haal detailinformatie als HTML op bij de bron"
            ),
        ),
        migrations.AlterField(
            model_name="linkeddata",
            name="popup_attributes",
            field=models.TextField(
                blank=True,
                help_text="Voer één veld per regel in. Bij geen invoer worden alle velden getoond.",
                max_length=250,
                null=True,
                verbose_name="Tabel velden",
            ),
        ),
    ]
