# Generated by Django 4.1.13 on 2024-02-13 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("webservice", "0112_layer_use_html_info_format_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="map",
            old_name="layers",
            new_name="old_layers",
        ),
        migrations.AlterField(
            model_name="map",
            name="old_layers",
            field=models.ManyToManyField(
                blank=True,
                related_name="old_layers",
                to="webservice.layer",
                verbose_name="Lagen",
            ),
        ),
        migrations.CreateModel(
            name="MapLayer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("settings", models.JSONField()),
                (
                    "layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maps_layer",
                        to="webservice.layer",
                    ),
                ),
                (
                    "map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="map_layers",
                        to="webservice.map",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="map",
            name="layers",
            field=models.ManyToManyField(
                blank=True,
                through="webservice.MapLayer",
                to="webservice.layer",
                verbose_name="Lagen",
            ),
        ),
    ]
