# Generated by Django 4.1.13 on 2024-02-13 10:59

from django.db import migrations
# from webservice.models import Map, MapLayer


def forwards_func(apps, _):
    Map = apps.get_model('webservice', 'Map')
    MapLayer = apps.get_model('webservice', 'MapLayer')

    for current_map in Map.objects.all():
        for layer in current_map.old_layers.all():
            MapLayer.objects.get_or_create(
                layer=layer,
                map=current_map,
                defaults={'settings': {'is_visible': True}}
            )


class Migration(migrations.Migration):
    dependencies = [
        (
            "webservice",
            "0113_map_old_layers_alter_category_slug_alter_layer_slug_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
