# Generated by Django 4.1.13 on 2024-05-15 11:11

from django.db import migrations

def forwards_func(apps, _):
    Map = apps.get_model('webservice', 'Map')

    for current_map in Map.objects.all():
        for layer in current_map.map_layers.all():
            if layer.settings == {"is_visible": True}:
                # If current settings value is {"is_visible": true}, update it to include customSettings: false
                layer.settings['customSettings'] = False
                layer.save()

class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0115_alter_maplayer_options_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
