# Generated by Django 4.1.13 on 2024-06-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0116_auto_20240515_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkeddata',
            name='detail_view_fields',
            field=models.TextField(blank=True, help_text='Voer één veld per regel in. Bij geen invoer worden alle velden getoond.', max_length=250, null=True, verbose_name='Detailweergave velden'),
        ),
        migrations.AddField(
            model_name='linkeddata',
            name='use_detail_view',
            field=models.BooleanField(default=False, verbose_name='Gebruik detailweergave'),
        ),
    ]
