# Generated by Django 4.1.13 on 2024-08-15 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0117_linkeddata_detail_view_fields_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Naam')),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='De naam van de dataset', max_length=128, verbose_name='Naam')),
                ('description', models.TextField(blank=True, help_text='Het is mogelijk om tekst op te maken met Markdown in dit veld', null=True, verbose_name='Beschrijving')),
                ('source_description', models.TextField(blank=True, help_text='Beschrijft de herkomst van de dataset. Het is mogelijk om tekst op te maken met Markdown in dit veld', null=True, verbose_name='Bron omschrijving')),
                ('organization', models.CharField(blank=True, max_length=128, null=True, verbose_name='Organisatie')),
                ('contact', models.CharField(blank=True, max_length=128, null=True, verbose_name='Contactpersoon')),
                ('data_owner', models.CharField(blank=True, max_length=128, null=True, verbose_name='Eigenaar van de data')),
                ('data_controller', models.CharField(blank=True, max_length=128, null=True, verbose_name='Data beheerder')),
                ('category', models.CharField(blank=True, max_length=128, null=True, verbose_name='Categorie')),
                ('last_updated', models.DateTimeField(blank=True, null=True, verbose_name='Laatste update')),
                ('update_frequency', models.CharField(blank=True, max_length=128, null=True, verbose_name='Update hoeveelheid')),
                ('purpose_of_manufacture', models.CharField(blank=True, max_length=128, null=True, verbose_name='Doel van de vervaardiging')),
                ('themes', models.ManyToManyField(related_name='datasets', to='webservice.theme')),
            ],
        ),
        migrations.AddField(
            model_name='layer',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layers', to='webservice.dataset'),
        ),
    ]
