# Generated by Django 4.1.13 on 2024-12-06 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0122_alter_dataset_options_alter_theme_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='owner',
        ),
    ]
