# Generated by Django 4.1.13 on 2025-02-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0125_alter_category_slug_alter_dataset_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='about',
            field=models.TextField(blank=True, help_text='Het is mogelijk om tekst op te maken met Markdown in dit veld', null=True, verbose_name='Beschrijving van de kaart voor de zijbalk'),
        ),
        migrations.AddField(
            model_name='map',
            name='about_title',
            field=models.CharField(blank=True, help_text='De titel van de zijbalk die gebruikt wordt in de zijbalkinformatie', max_length=128, null=True, verbose_name='Titel van de zijbalk'),
        )
    ]
