# Generated by Django 4.1.13 on 2025-02-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_alter_atlasgroup_slug'),
        ('webservice', '0125_alter_category_slug_alter_dataset_published_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layer',
            old_name='atlas_groups',
            new_name='read_groups',
        ),
        migrations.AlterField(
            model_name='layer',
            name='read_groups',
            field=models.ManyToManyField(blank=True, help_text='De inhoud van deze dataset kan alleen bekeken worden als de gebruiker lid is van een van deze groepen.', related_name='read_groups', to='user_management.atlasgroup', verbose_name='Groepen met leesrecht'),
        ),
    ]
