# Generated by Django 4.1.13 on 2025-02-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_alter_atlasgroup_slug'),
        ('webservice', '0126_remove_layer_atlas_groups_layer_read_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='write_groups',
            field=models.ManyToManyField(blank=True, help_text='De inhoud van deze dataset kan alleen bewerkt worden als de gebruiker lid is van een van deze groepen.', related_name='write_groups', to='user_management.atlasgroup', verbose_name='Groepen met schrijfrecht'),
        ),
    ]
