# Generated by Django 4.1.13 on 2025-03-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('webservice', '0128_alter_category_slug_alter_dataset_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='is_filterable_in_legend',
            field=models.BooleanField(default=False, verbose_name='Laag is filterbaar in legenda'),
        ),
    ]
