# Generated by Django 4.1.13 on 2025-03-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0129_layer_is_filterable_in_legend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='extent_max_x',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Bereik maximum x'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='extent_max_y',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Bereik maximum y'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='extent_min_x',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Vul in om de laag inactief te maken wanneer de weergave buiten het bereik ligt.', max_digits=10, null=True, verbose_name='Bereik minimum x'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='extent_min_y',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Bereik minimum y'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='zoom_max',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, verbose_name='Zoomniveau maximum'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='zoom_min',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Vul in om de laag inactief te maken wanneer de weergave buiten het zoomniveau ligt.', max_digits=5, null=True, verbose_name='Zoomniveau minimum'),
        ),
    ]
