# Generated by Django 4.1.13 on 2025-04-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_alter_atlasgroup_slug'),
        ('webservice', '0130_alter_layer_extent_max_x_alter_layer_extent_max_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='atlas_write_groups',
            field=models.ManyToManyField(blank=True, help_text='De inhoud van deze dataset kan alleen gemuteerd worden als de gebruiker lid is van een van deze groepen.', related_name='atlas_write_groups', to='user_management.atlasgroup', verbose_name='Groepen'),
        ),
    ]
