# Generated by Django 4.1.13 on 2025-05-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0130_alter_layer_extent_max_x_alter_layer_extent_max_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='_search_terms',
            field=models.CharField(blank=True, help_text='Deze worden gebruikt om de laag beter vindbaar te maken in het lagenpaneel. Voer één zoekterm per regel in.', max_length=500, null=True, verbose_name='Zoektermen'),
        ),
    ]
