# Generated by Django 4.1.13 on 2025-04-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0131_layer_atlas_write_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='authenticated_can_mutate',
            field=models.BooleanField(default=False, help_text='Alle ingelogde gebruikers kunnen wanneer deze optie aanstaat kaartlagen muteren', verbose_name='Ingelogde gebruikers kunnen kaartlaag muteren'),
        ),
    ]
