# Generated by Django 4.1.13 on 2025-06-02 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0131_layer__search_terms'),
        ('webservice', '0132_layer_authenticated_can_mutate'),
    ]

    operations = [
    ]
