# Generated by Django 4.1.13 on 2025-06-24 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0133_merge_20250602_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maplayer',
            options={'ordering': ['layer__layer_type__ordering', 'layer__ordering', 'layer__title'], 'verbose_name': 'Kaartlaag', 'verbose_name_plural': 'Kaartlagen'},
        ),
    ]
