# Generated by Django 4.1.13 on 2025-07-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0134_alter_maplayer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='is_exportable',
            field=models.BooleanField(default=True, verbose_name='Kaartlaag is exporteerbaar'),
        ),
    ]
