# Generated by Django 4.1.13 on 2025-08-18 14:45

from django.db import migrations, models
from django.db.models import Count, Min


# dedupe map layers if present
def dedupe_maplayers(apps, schema_editor):
    MapLayer = apps.get_model('webservice', 'MapLayer')

    dupes = (
        MapLayer.objects
        .values('map_id', 'layer_id')
        .annotate(count=Count('id'), keep_id=Min('id'))
        .filter(count__gt=1)
    )

    for d in dupes.iterator():
        (MapLayer.objects
         .filter(map_id=d['map_id'], layer_id=d['layer_id'])
         .exclude(id=d['keep_id'])
         .delete())


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0135_layer_is_exportable'),
    ]

    operations = [
        migrations.RunPython(dedupe_maplayers, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='maplayer',
            constraint=models.UniqueConstraint(fields=('layer', 'map'), name='unique_map_layer'),
        ),
    ]
