# Generated by Django 4.1.13 on 2025-01-27 10:00

from django.db import migrations
from django.utils.text import slugify
from dateutil import parser

def parse_flexible_date(date_string):
    """Parse various date formats, defaulting to day-first European style."""
    if not date_string:
        return None
    try:
        return parser.parse(date_string, dayfirst=True).date()
    except (ValueError, TypeError):
        return None

def create_metadatasets_from_layers(apps, _):
    """
    For each layer, create a metadataset using the layer's metadata fields
    and then link the metadataset back to the layer.
    """
    layer_model = apps.get_model('webservice', 'Layer')
    metadataset_model = apps.get_model('webservice', 'Metadataset')

    for layer in layer_model.objects.iterator():

        # Skip if layer already has a metadataset
        if layer.metadataset:
            continue

        # Get metadata fields from layer
        meta_name = layer.meta_name or f"Metadata voor {layer.title}"
        meta_description = layer.meta_description or ""
        meta_lineage = layer.meta_lineage or ""
        meta_org = layer.meta_org or ""
        meta_contact = layer.meta_contact or ""
        meta_updated = layer.meta_updated or ""
        meta_link = layer.meta_link or ""

        # Skip if all metadata fields are empty
        if not any([
            layer.meta_name, layer.meta_description, layer.meta_lineage,
            layer.meta_org, layer.meta_contact, layer.meta_updated, layer.meta_link
        ]):
            continue

        # Create metadataset with layer metadata
        # Generate unique slug
        base_slug = slugify(meta_name) if meta_name else "metadata"
        slug = base_slug
        counter = 1
        while metadataset_model.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1

        metadataset = metadataset_model.objects.create(
            title=meta_name,
            slug=slug,
            description=meta_lineage,
            abstract=meta_description,
            source_origin=meta_link,
            source_organization=meta_org,
            source_email_internal=meta_contact,
            last_updated=parse_flexible_date(meta_updated),
            # Set some default values for required fields
            update_method='manual',
            show_in_overview=False,
            status='completed'
        )

        # Link the metadataset back to the layer
        layer.metadataset = metadataset
        layer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0136_metadataset_and_layer_updates'),
    ]

    operations = [
        migrations.RunPython(create_metadatasets_from_layers),
    ]
