# Generated by Django 4.1.13 on 2025-09-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0136_maplayer_unique_map_layer'),
        ('webservice', '0137_add_metadataset_to_layer'),
    ]

    operations = [
    ]
