# Generated by Django 5.2.6 on 2025-11-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0138_merge_20250911_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadataset',
            name='source_name_internal',
            field=models.CharField(blank=True, help_text='De naam van de contactpersoon van het interne aanspreekpunt van de bron.', max_length=128, null=True, verbose_name='Naam contactpersoon aanspreekpunt'),
        ),
        migrations.AddField(
            model_name='metadataset',
            name='source_name_public',
            field=models.CharField(blank=True, help_text='De naam van de verantwoordelijke contactpersoon van de bron.', max_length=128, null=True, verbose_name='Naam contactpersoon verantwoordelijke'),
        ),
    ]
