# Generated by Django 5.2.6 on 2025-12-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_v2', '__first__'),
        ('webservice', '0138_merge_20250911_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='related_tables',
            field=models.ManyToManyField(related_name='layers', through='tables_v2.LayerToTable', to='tables_v2.tabletemp'),
        ),
    ]
