# Generated by Django migration

from django.db import migrations


def copy_meta_contact_to_source_name_internal(apps, schema_editor):
    """
    Copy layer.meta_contact to metadataset.source_name_internal for all layers
    that have a metadataset. This ensures the previously contact information
    remains accessible in the internal name field.
    """
    Layer = apps.get_model('webservice', 'Layer')

    for layer in Layer.objects.filter(metadataset__isnull=False).select_related('metadataset'):
        if layer.meta_contact and layer.meta_contact.strip():
            metadataset = layer.metadataset
            # Only update if source_name_internal is empty to avoid overwriting existing data
            if not metadataset.source_name_internal or not metadataset.source_name_internal.strip():
                metadataset.source_name_internal = layer.meta_contact.strip()
                metadataset.save(update_fields=['source_name_internal'])


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0139_metadataset_meta_name_internal_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_meta_contact_to_source_name_internal),
    ]

