# Generated by Django 5.2.6 on 2025-11-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0140_copy_layer_meta_contact_to_metadataset_source_name_internal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadataset',
            name='meta_email_internal',
            field=models.EmailField(blank=True, help_text='Het e-mailadres van het interne aanspreekpunt van de verantwoordelijke van de metadata.', max_length=254, null=True, verbose_name='E-mailadres aanspreekpunt'),
        ),
        migrations.AlterField(
            model_name='metadataset',
            name='source_email_internal',
            field=models.EmailField(blank=True, help_text='Het e-mailadres van het interne aanspreekpunt van de bron.', max_length=254, null=True, verbose_name='E-mailadres aanspreekpunt'),
        ),
    ]
