# Generated by Django 5.2.6 on 2025-12-09 12:59

import django.core.validators
import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0141_alter_metadataset_meta_email_internal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, default=None, editable=False, help_text='Een uniek kort kenmerk voor de categorie in Atlas.', max_length=255, populate_from='title', unique=True, validators=[django.core.validators.RegexValidator(message="Slugs mogen alleen letters, cijfers en koppeltekens ('-') bevatten.", regex='^[a-zA-Z0-9-]+$')], verbose_name='Kort kenmerk'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, default=None, editable=False, help_text='Een uniek kenmerk voor de laag in Atlas. Dit kenmerk komt terug in links naar de laag.)', max_length=255, null=True, populate_from='title', unique=True, validators=[django.core.validators.RegexValidator(message="Slugs mogen alleen letters, cijfers en koppeltekens ('-') bevatten.", regex='^[a-zA-Z0-9-]+$')], verbose_name='Kort kenmerk'),
        ),
        migrations.AlterField(
            model_name='map',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='Een uniek kort kenmerk voor de kaart in Atlas.', max_length=255, populate_from='title', unique=True, validators=[django.core.validators.RegexValidator(message="Slugs mogen alleen letters, cijfers en koppeltekens ('-') bevatten.", regex='^[a-zA-Z0-9-]+$')], verbose_name='Kort kenmerk'),
        ),
        migrations.AlterField(
            model_name='metadataset',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, default=None, editable=False, help_text='Een uniek kort kenmerk voor de metadataset in Atlas. Gebruik alleen kleine letters, cijfers en afbreekstreepjes.', max_length=255, null=True, populate_from='title', unique=True, validators=[django.core.validators.RegexValidator(message="Slugs mogen alleen letters, cijfers en koppeltekens ('-') bevatten.", regex='^[a-zA-Z0-9-]+$')], verbose_name='Kort kenmerk'),
        ),
        migrations.AlterField(
            model_name='selection',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='Een uniek kort kenmerk voor de kaartselectie in Atlas.', max_length=255, populate_from='title', unique=True, validators=[django.core.validators.RegexValidator(message="Slugs mogen alleen letters, cijfers en koppeltekens ('-') bevatten.", regex='^[a-zA-Z0-9-]+$')], verbose_name='Kort kenmerk'),
        ),
        migrations.AlterField(
            model_name='source',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, default=None, editable=False, help_text='Een uniek kort kenmerk voor de bron in Atlas.', max_length=255, null=True, populate_from='title', unique=True, validators=[django.core.validators.RegexValidator(message="Slugs mogen alleen letters, cijfers en koppeltekens ('-') bevatten.", regex='^[a-zA-Z0-9-]+$')], verbose_name='Kort kenmerk'),
        ),
    ]
