# Generated by Django 5.2.6 on 2025-12-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0142_alter_category_slug_alter_layer_slug_alter_map_slug_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Selection',
        ),
    ]
