# Generated by Django 5.2.6 on 2025-12-18 09:27

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0143_delete_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, default=None, editable=False, help_text='Een uniek kort kenmerk voor de categorie in Atlas.', max_length=255, populate_from='title', unique=True, verbose_name='Kort kenmerk'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, default=None, editable=False, help_text='Een uniek kenmerk voor de laag in Atlas. Dit kenmerk komt terug in links naar de laag.)', max_length=255, null=True, populate_from='title', unique=True, verbose_name='Kort kenmerk'),
        ),
        migrations.AlterField(
            model_name='source',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, default=None, editable=False, help_text='Een uniek kort kenmerk voor de bron in Atlas.', max_length=255, null=True, populate_from='title', unique=True, verbose_name='Kort kenmerk'),
        ),
    ]
