# Generated by Django 5.2.9 on 2026-02-05 11:05

import django.db.models.deletion
from django.db import migrations, models

from ._0145_create_map_categories import create_map_categories


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0144_alter_category_slug_alter_layer_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maplayer',
            options={'ordering': ['map_category__ordering', 'ordering', 'layer__title'], 'verbose_name': 'Kaartlaag', 'verbose_name_plural': 'Kaartlagen'},
        ),
        migrations.AddField(
            model_name='maplayer',
            name='ordering',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Sortering'),
        ),
        migrations.CreateModel(
            name='MapCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Sortering')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps_category', to='webservice.category')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_categories', to='webservice.map')),
            ],
            options={
                'verbose_name': ('Kaartcategorie',),
                'verbose_name_plural': ('Kaartcategorieën',),
                'ordering': ['ordering', 'category__title'],
            },
        ),
        migrations.AddField(
            model_name='maplayer',
            name='map_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map_layers', to='webservice.mapcategory'),
        ),
        migrations.AddConstraint(
            model_name='mapcategory',
            constraint=models.UniqueConstraint(fields=('category', 'map'), name='unique_map_category'),
        ),
        migrations.RunPython(create_map_categories, reverse_code=migrations.RunPython.noop),
    ]
