# Generated by Django 5.2.6 on 2026-02-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0144_alter_category_slug_alter_layer_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='keywords',
            field=models.TextField(blank=True, help_text='Zoektermen om de kaart te vinden in het dataportaal. Eén zoekterm per regel.', null=True, verbose_name='Zoektermen'),
        ),
    ]
