# Generated by Django 5.2.9 on 2026-02-24 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0145_map_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadataset',
            name='source_email_person_responsible',
        ),
    ]
