# Generated by Django 5.2.9 on 2026-02-20 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0145_alter_maplayer_options_maplayer_ordering_mapcategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapcategory',
            options={'ordering': ['ordering', 'category__title'], 'verbose_name': 'Kaartcategorie', 'verbose_name_plural': 'Kaartcategorieën'},
        ),
    ]
