# Generated by Django 5.2.9 on 2026-02-24 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0145_map_keywords'),
        ('webservice', '0146_alter_mapcategory_options'),
    ]

    operations = [
    ]
