# Generated by Django 5.2.9 on 2026-03-03 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0146_remove_metadataset_source_email_person_responsible'),
        ('webservice', '0147_merge_20260224_1004'),
    ]

    operations = [
    ]
