# Generated by Django 5.2.12 on 2026-04-08 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0150_alter_layer_closed_dataset'),
        ('webservice', '0150_map_is_main'),
    ]

    operations = [
    ]
