# Generated by Django 5.2.12 on 2026-04-09 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0152_map_position_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='not_in_atlas',
        ),
    ]
