# Generated by Django 5.2.12 on 2026-06-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0155_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='is_reference_date_enabled',
            field=models.BooleanField(default=False, verbose_name='Peildatumweergave inschakelen'),
        ),
        migrations.AddField(
            model_name='layer',
            name='is_time_enabled',
            field=models.BooleanField(default=False, verbose_name='Tijdlijn inschakelen'),
        ),
        migrations.AddField(
            model_name='layer',
            name='time_slider_default_display_mode',
            field=models.CharField(choices=[('period', 'Periode'), ('referenceDate', 'Peildatum')], default='period', max_length=20, verbose_name='Standaardweergave tijdlijn'),
        ),
        migrations.AddField(
            model_name='layer',
            name='time_slider_end_field',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Einddatumveld (GeoServer TIME)'),
        ),
        migrations.AddField(
            model_name='layer',
            name='time_slider_start_field',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Startdatumveld (GeoServer TIME)'),
        ),
    ]
