# Generated by Django 5.2.12 on 2026-06-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0156_layer_is_reference_date_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadataset',
            name='fme_script',
            field=models.CharField(blank=True, help_text='Naam of pad van de FME-workspace of script waarmee de dataset wordt bijgewerkt. Alleen zichtbaar in Atlas Admin.', max_length=512, null=True, verbose_name='FME-script'),
        ),
        migrations.AlterField(
            model_name='metadataset',
            name='abstract',
            field=models.TextField(blank=True, help_text='Een beschrijving van de inhoud van de dataset, geef in deze samenvatting publieksvriendelijke informatie over de inhoud van de dataset. Deze is minimaal drie zinnen en maximaal één alinea lang (2000 karakters).', null=True, verbose_name='Toelichting dataset'),
        ),
    ]
