# Generated by Django 5.2.15 on 2026-09-02 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0159_layer_disable_highlighted_style'),
        ('webservice', '0159_move_layer_base_visibility_to_maplayer'),
    ]

    operations = [
    ]
