# Generated by Django 5.2.15 on 2026-09-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0160_merge_20260902_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='is_clustered',
            field=models.BooleanField(
                default=False,
                help_text='Cluster objecten die dicht bij elkaar staan op de kaart.',
                verbose_name='Objecten clusteren',
            ),
        ),
    ]
