site_name: Atlas Admin module Documentatie
site_url: https://127.0.0.1:8808
dev_addr: '127.0.0.1:8808'
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  language: nl
  palette:
    primary: custom
  features:
    - navigation.footer
extra:
  generator: false
plugins:
  - search
markdown_extensions:
  - smarty
  - toc:
      separator: "-"
nav:
  - 'Admin documentatie': 'index.md'
  - 'Installatie': 'installlokaal.md'
  - 'Beveiliging': 'layer_security.md'
