apiVersion: v2
name: atlas
description: Atlas is a geo portal that provides a user-friendly interface.

type: application

version: 3.53.0
appVersion: 3.53.0

dependencies:
  - name: postgresql
    version: 18.1.3
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - postgresql
  - name: geoserver
    version: 2.27.3
    repository: https://delta10.github.io/helm-charts
    condition: geoserver.enabled
    tags:
      - geoserver
  - name: filter-proxy
    version: 0.8.2
    repository: https://delta10.github.io/helm-charts
    condition: filter-proxy.enabled
    tags:
      - filter-proxy
