tags:
  postgresql: true

replicaCount: 1

image:
  repository: registry.gitlab.com/purmerend/atlas
  tag: ""
  pullPolicy: IfNotPresent

podAnnotations: {}

debug: false
secretKey: something-secret
allowedHosts: atlas.example.com

internalIps: ""
adminIps: ""

dbHost: atlas-postgresql
dbUser: atlas
dbPassword: change-to-something-secret
dbName: atlas

loadDemoData: false

environment: production

existingSecret: null # Refer to existing secret to avoid managing secrets through Helm

smartstreetUser: ""
smartstreetPassword: ""
smartstreetApiKey: ""

googleMapsApiKey: ""

sentryDsn: ""

matomoUrl: ""
matomoSiteId: ""

authenticationEnableCredentials: true
authenticationEnableOidc: false

oidcClientId: atlas
oidcClientSecret: somethingsecret
oidcSignAlgo: RS256
oidcScopes: openid email profile
oidcAuthorizationEndpoint: http://localhost:6556/auth
oidcTokenEndpoint: http://localhost:6556/token
oidcUserEndpoint: http://localhost:6556/userinfo
oidcJwksEndpoint: http://localhost:6556/keys
oidcUsernameClaim: sub
oidcActivateOnCreate: true
oidcSyncGroups: false

showLayersOnlyWhenAccessible: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext:
  fsGroup: 33

securityContext: {}

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
  annotations:
    {}
  # cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: atlas.example.com
      paths:
        - path: /atlas
          pathType: ImplementationSpecific
  tls: []
  #   - secretName: atlas-tls
  #     hosts:
  #       - atlas.example.com

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  media:
    enabled: true
    size: 1Gi
    existingClaim: null
    accessModes:
      - ReadWriteOnce
    storageClassName: "local-path"

#########################
## PostgreSQL subchart ##
#########################
postgresql:
  image:
    repository: bitnamilegacy/postgresql
    tag: 17.5.0-debian-12-r9

  auth:
    username: atlas
    password: change-to-something-secret
    database: atlas

########################
## Geoserver subchart ##
########################
geoserver:
  enabled: false
  image:
    tag: "2.27.3-1"
  persistence:
    accessModes:
      - ReadWriteOnce
  env:
    GEOSERVER_CSRF_WHITELIST: "geoserver-example.com"
    EXTRA_JAVA_OPTS: -Xms256m -Xmx2048m
  resources:
    limits:
      cpu: 1000m
      memory: 4Gi
    requests:
      cpu: 10m
      memory: 24Mi
  ingress:
    enabled: true
    className: ""
    annotations:
      {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths:
          - path: /geoserver
            pathType: ImplementationSpecific
    tls: []

###########################
## Filter-proxy subchart ##
###########################
filter-proxy:
  enabled: false
  service:
    port: 8050
  config:
    listenAddress: 0.0.0.0:8050
    authorizationServiceUrl: http://host.docker.internal:8000/atlas/api/v1/authorize/
    cors:
      allowedOrigins:
        - http://host.docker.internal:8000
      allowedHeaders:
        - Accept
        - Authorization
        - Content-Type
        - X-Requested-With
      allowCredentials: true
      allowPrivateNetwork: true
      debugLogging: true
    paths:
      - path: /api/ows
        backend:
          slug: geoserver
          path: /ows
        allowedMethods:
          - GET
          - POST
      - path: /api/kvk/zoeken
        backend:
          slug: kvk
          path: /zoeken
      - path: /api/dso/_zoek
        backend:
          slug: dso
          path: /_zoek
        allowedMethods:
          - POST
        requestRewrite: |
          {
              "geometrie": {
                  "type": "Point",
                  "coordinates": [
                      .latitude,
                      .longitude
                  ]
              }
          }
      - path: /api/dso/{uriIdentificatie}
        backend:
          slug: dso
          path: /{uriIdentificatie}
        allowedMethods:
          - GET
    backends:
      geoserver:
        type: OWS
        baseUrl: http://host.docker.internal:8080/geoserver
      kvk:
        type: REST
        baseUrl: https://api.kvk.nl/test/api/v2
        auth:
          header:
            apikey: l7xx1f2691f2520d487b902f4e0b57a0b197
      dso:
        type: REST
        baseUrl: https://service.omgevingswet.overheid.nl/publiek/omgevingsinformatie/api/ontsluiten/v2/documenten
        auth:
          header:
            x-api-key: ${DSO_API_KEY}
            content-crs: http://www.opengis.net/def/crs/EPSG/0/28992
            content-type: application/json
