name: Release Helm Chart
on:
  workflow_dispatch: {}
  push:
    branches: ["chore/helm-publish"]

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: geo-commons/charts
  CHART_NAME: atlas

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Helm | Login
        id: login
        run: echo ${{ secrets.GITHUB_TOKEN }} | helm registry login -u ${{ github.actor }} --password-stdin $REGISTRY/geo-commons

      - name: Get versions
        id: version
        run: |
          VERSION=$(yq .version helm/Chart.yaml)
          LATEST=$(helm show chart oci://$REGISTRY/$IMAGE_PREFIX/$CHART_NAME 2>/dev/null|yq '.version')
          echo "Latest version: $LATEST"
          echo "Updating to version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "latest=$LATEST" >> $GITHUB_OUTPUT

      - name: Helm | Package
        if: steps.version.outputs.version != steps.version.outputs.latest
        run: |
          cd helm
          helm repo add helm https://charts.helm.sh/stable
          helm repo add delta10 https://delta10.github.io/helm-charts
          helm dependency build
          helm package .

      - name: Helm | Push
        if: steps.version.outputs.version != steps.version.outputs.latest
        run: |
          VERSION=${{ steps.version.outputs.version }}
          helm push ./$CHART_NAME-$VERSION.tgz oci://$REGISTRY/$IMAGE_PREFIX

      - name: Helm | Logout
        if: always()
        run: helm registry logout $REGISTRY/geo-commons
