# Generated by Django 5.2.9 on 2026-02-11 12:24

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webservice', '0144_alter_category_slug_alter_layer_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerToTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_mapping', models.JSONField(verbose_name='Mapping van kolomnamen')),
                ('from_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_table_relations', to='webservice.layer')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='De naam van de tabel', max_length=128, verbose_name='Naam')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, default=None, editable=False, help_text='Een uniek kort kenmerk voor de tabel in Atlas. Gebruik alleen kleine letters, cijfers en afbreekstreepjes.', max_length=255, null=True, populate_from='title', unique=True, verbose_name='Kort kenmerk')),
                ('source_type', models.CharField(choices=[('OWS', 'OWS'), ('WMTS', 'WMTS'), ('REST', 'REST')], default='OWS', verbose_name='Brontype')),
                ('fields', models.JSONField(default=list)),
                ('list_endpoint', models.CharField(blank=True, max_length=1024, null=True, verbose_name='List endpoint')),
                ('detail_endpoint', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Detail endpoint')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=20, verbose_name='Methode')),
                ('request_body', models.JSONField(default=dict, verbose_name='Request body (voor POST)')),
                ('list_property', models.CharField(blank=True, max_length=255, null=True, verbose_name='Veldnaam van lijst')),
                ('detail_property', models.CharField(blank=True, max_length=255, null=True, verbose_name='Veldnaam van detailweergave')),
                ('page_param', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL parameter voor pagina')),
                ('start_page_index', models.IntegerField(default=0, help_text='De index waarop de paginering start. Standaard is 0.', verbose_name='Startindex pagina')),
                ('items_per_page_param', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL parameter voor items per pagina')),
                ('total_items_page_property', models.CharField(blank=True, max_length=255, null=True, verbose_name='Veldnaam van totaal aantal items')),
                ('list_error_property', models.CharField(blank=True, max_length=255, null=True, verbose_name='Veldnaam van foutmelding in lijstweergave')),
                ('detail_error_property', models.CharField(blank=True, max_length=255, null=True, verbose_name='Veldnaam van foutmelding detailweergave')),
                ('template_fields', models.JSONField(default=dict, verbose_name='Templatevelden')),
                ('layer_name', models.CharField(help_text='De naam van de laag op de geoserver.', max_length=128, null=True, verbose_name='Laagnaam')),
                ('list_cql_filters', models.JSONField(default=dict)),
                ('detail_cql_filters', models.JSONField(default=dict)),
                ('list_display_properties', models.JSONField(default=list, help_text='Lijst van kolomnamen die getoond worden in de lijstweergave', verbose_name='Kolommen voor lijstweergave')),
                ('detail_display_properties', models.JSONField(default=list, help_text='Lijst van kolomnamen die getoond worden in de detailweergave', verbose_name='Kolommen voor detailweergave')),
                ('layers', models.ManyToManyField(related_name='related_tables', through='table.LayerToTable', to='webservice.layer')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='webservice.source')),
            ],
            options={
                'verbose_name': 'Tabel',
                'verbose_name_plural': 'Tabellen',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='layertotable',
            name='to_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_table_relations', to='table.table'),
        ),
        migrations.CreateModel(
            name='TableToTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_mapping', models.JSONField(verbose_name='Mapping van kolomnamen')),
                ('from_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_table_relations', to='table.table')),
                ('to_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_table_relations', to='table.table')),
            ],
            options={
                'unique_together': {('from_table', 'to_table')},
            },
        ),
        migrations.AddField(
            model_name='table',
            name='tables',
            field=models.ManyToManyField(related_name='related_tables', through='table.TableToTable', to='table.table'),
        ),
        migrations.AlterUniqueTogether(
            name='layertotable',
            unique_together={('from_layer', 'to_table')},
        ),
    ]
