# Generated by Django 5.2.9 on 2026-03-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='login_required',
            field=models.BooleanField(default=False, help_text='De tabel is alleen zichtbaar voor ingelogde gebruikers, ook als deze gekoppeld is aan andere tabellen.', verbose_name='Vereis inlog voor deze tabel'),
        ),
        migrations.AddField(
            model_name='table',
            name='show_in_portal',
            field=models.BooleanField(default=False, verbose_name='Toon in portal'),
        ),
    ]
