# Generated by Django 5.2.12 on 2026-04-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_table_login_required_table_show_in_portal'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='disable_detail_view',
            field=models.BooleanField(default=False, help_text='Schakel de detailweergave uit voor deze tabel', verbose_name='Detailweergave uitschakelen'),
        ),
    ]
