# Generated by Django 5.2.12 on 2026-04-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_table_disable_detail_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='friendly_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Maak veldnamen vriendelijk', null=True, verbose_name='Vriendelijke veldnamen'),
        ),
    ]
