# Generated by Django 5.2.12 on 2026-04-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_table_friendly_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='layertotable',
            name='related_table_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titel van gerelateerde tabel'),
        ),
        migrations.AddField(
            model_name='tabletotable',
            name='related_table_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titel van gerelateerde tabel'),
        ),
    ]
