# Generated by Django 5.2.12 on 2026-04-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_layertotable_title_tabletotable_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='list_template_fields',
            field=models.JSONField(default=dict, verbose_name='Templatevelden voor lijstweergave'),
        ),
    ]
