# Generated by Django 5.2.12 on 2026-04-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("table", "0006_table_list_template_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="friendly_search_fields",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Vriendelijke zoekingangen",
                null=True,
                verbose_name="Vriendelijke zoekingangen",
            ),
        ),
    ]
