# Generated by Django 5.2.12 on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("table", "0007_table_friendly_search_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="layertotable",
            name="ordering",
            field=models.PositiveIntegerField(default=0, verbose_name="Volgorde"),
        ),
        migrations.AddField(
            model_name="tabletotable",
            name="ordering",
            field=models.PositiveIntegerField(default=0, verbose_name="Volgorde"),
        ),
        migrations.AlterModelOptions(
            name="layertotable",
            options={"ordering": ["ordering", "id"]},
        ),
        migrations.AlterModelOptions(
            name="tabletotable",
            options={"ordering": ["ordering", "id"]},
        ),
    ]
